ow_lander/scripts/activity_full_digging_traj.py

Ticket: https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-445
This is to avoid collision between grinder and terrain during scooping, in particular DigCircular when radial==False. I implemented both Ussama's suggestion of reducing the hand rotation and Terry's suggestion of relocating the grinder to a 180 deg angle from the scoop. Both work, but Ussama's approach is simpler and avoids the "floating grinder" visualization. So I pushed only this one. I have Terry's approach in another local branch, which I didn't push.
Try calling DigCircular and check that there is collision. Try calling other services that might be compromised by this modification. Let me know your thoughts, thanks!

reduced hand rotation in DigCircular

---

ow_dynamic_terrain/CMakeLists.txt
ow_dynamic_terrain/README.md
ow_dynamic_terrain/include/MergeMethods.h
ow_dynamic_terrain/include/TerrainModifier.h
ow_dynamic_terrain/include/memory_ext.h
ow_dynamic_terrain/scripts/modify_terrain_grinder_pub.py
ow_dynamic_terrain/scripts/modify_terrain_scoop_pub.py
ow_dynamic_terrain/src/DynamicTerrainBase.cpp
ow_dynamic_terrain/src/DynamicTerrainBase.h
ow_dynamic_terrain/src/DynamicTerrainModel.cpp
ow_dynamic_terrain/src/DynamicTerrainVisual.cpp
ow_lander/urdf/lander.xacro

* Collision between the terrain and the end effectors is now enabled
* Topics corresponding to /ow_dynamic_terrain/modify_terrain_* are left intact. Plugin-specific topics {visual and collision} are added to the *DynamicTerrainVisual* and *DynamicTerrainModel* plugins
* Python scripts `modify_terrain_scoop_pub.py` and `modify_terrain_grinder_pub.py` corresponding to the scoop and grinder has been updated to use the Plugin-specific topics with a slightly different parameters for visual vs collision.
- The `modify_terrain_*/collision` message is merely a scaled up version of the `modify_terrain_*/visual` message  
* README file updated with the new changes
Launch the simulation against the `europa_terminator_workspace`:
```bash
roslaunch ow europa_terminator_workspace.launch
```
Use the rqt …

OCEANWATER-346: Use a different topic name for dynamic terrain model and visual plugins

---

ow_lander/CMakeLists.txt
ow_lander/msg/GuardedMoveResult.msg
ow_lander/scripts/trajectory_publisher.py

Hello!
Ticket: https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-434
Background:
We agreed some time ago that, after publishing guarded_move, there should be a message containing the following information: has ground been found successfully? What are the coordinates of the ground? In which reference frame? Autonomy will use this info to store the ground height at that specific location and feed it to the digging services. 
What I did here:
- I use the existing node "trajectory_publisher" to publish a message on a new topic, at the end of publish_trajectory for guarded_move. 
- the message is defined in ow_lander>msg, called "GuardedMoveResult.msg"
- the topic is called: "/guarded_move_result".
How to test:
- Terminal 1: roslaunch ow europa_terminator_workspace.launch
- Terminal 2: 
a) …

trajectory_publisher node publishes message with guarded_move result when guarded_move is published, for autonomy

---

ow_lander/scripts/peak_detection_real_time.py
ow_lander/scripts/trajectory_publisher.py

This PR improves and addresses several issues in current implementation/integration of the ground detection:
The improvements include:
- Scan velocity samples only once
- Catch peaks that could have been missed
- Make sure that the peak detector state is reset on every invocation (to enable invoking multiple times in one session).
- Limit resource usage
Launch the simulation using
```bash
roslaunch ow europa_terminator_workspace.launch
```
Then plan a guarded move and execute it.
Try Invoking the plan multiple times in one session.
Report how to often do you successfully get the ground detected signal. This doesn't address making the ground detection robust yet. See the note down below. 
- Verify functionality described
- Verify that this change didn't break any existing functionality …

Oceanwater 457 refactor thresholding algo to scan samples once

---

ow_dynamic_terrain/scripts/modify_terrain_grinder_pub.py
ow_dynamic_terrain/scripts/modify_terrain_scoop_pub.py
ow_dynamic_terrain/src/TerrainModifier.cpp
ow_lander/urdf/lander.xacro

+ Ensure the same digging values works for all terrains
+ Grinder only affects 1/3 of the value
+ Enable collision for scoop and grinder
```bash
roslaunch ow europa_terminator_workspace.launch
```
or
```bash
```
and then perform the grind operation followed by a scoop. Note that scooping now collides with the terrain.
* Check that the grind operation affects all the terrain in same manner (in particular atacama and terminator_workspace).
* Check that the Scoop operation no longer updates the collision.
* Check that the Scoop operation only updates the terrain visuals.
* Any suggestions or improvements that can be made to make this work better.
Linked Issue: https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-471

Refine digging collision and deformation

---

ow_lander/scripts/ground_detection.py

Significantly improved ground detection by tracking the **trending value** of the arm movement speed and use it to decide if the arm reached ground or not. 
Launch the simulation against the europa_terminator_workspace and atacama_y1a
```bash
roslaunch ow europa_terminator_workspace.launch
```
or
```bash
```
Use __ros service caller__ or your favorite method to perform the invoked guarded detection command.
Observe whether the ground detection takes place at the instant the scoop touches the ground. This should perform better than before as I was able to lower the threshold value with the latest changes.
**Note:** Even though I compute the arm movement in 3d but the current criterion to detect ground use only on the z values for decision making. The reason …

Threshold ground detection based on velocity trend

---

ow_lander/scripts/ground_detection.py

A quick fix that provides the ground position as a a geometry Point message object as the trajectory publisher expects

return Point object for trajectory_publisher

---

oceanwaters/workspaces/oceanwaters.rosinstall

The git URLs we are using are different from the ones that github gives you to clone code. Both work. But if you clone a repo using github's URL and then do a wstool up, you get this:
```
Url https://github.com/nasa/irg_open does not match https://github.com/nasa/irg_open.git requested.
(d)elete and replace, (a)bort, (b)ackup and replace, (s)kip:
```
This ticket just changes to use github's URLs in our .rosinstall file. It will cause a little confusing in the near term but may save developers that confusion later on. Consistency is good.

Use git URLs identical to the ones on github.

---

ow_lander/config/ompl_planning.yaml
ow_lander/scripts/activity_grind.py

**ABOUT THIS BRANCH**
While reviewing the renovated grinder service, @Samahu noticed that the arm would make an unnecessary motion before the grinder penetrates the terrain. Here is the video: https://www.youtube.com/watch?v=IytOorLmMf8 . This raised a question on whether the planner is actually optimizing the motion for something in particular. I did some research and discovered the following.
- In OceanWATERS we use two planners: RRTconnect and RRTstar. RRT connect is not an optimal planner. The basic idea behind RRTconnect is to grow two trees, one from the start and one from the goal, and attempt to connect them.
- RRTstar is an optimal planner. For RRTstar, the following optimization objectives are available: PathLengthOptimizationObjective (Default), …

Oceanwater 487 energy efficient planner

---

ow_lander/scripts/path_planning_commander.py

Increase the timeout for MoveGroupCommander(s) to 15 seconds to address an issue where MoveGroupCommander(s) are taking time quite sometime before they become responsive again after an operation has finished
If you want to see the problem reset the timeouts of every _MoveGroupCommander_ to their default value of 5s and run the simulation against atacama and then run the reference mission (try more than one attempt).
```bash
```
and
```bash
roslaunch ow_autonomy autonomy_node.launch plan:=ReferenceMission1.plx
```
Pay attention to the ow_simulator logs and notice the RuntimeError is thrown at some point after the first guarded move attempt (Consequently the autonomy node may also fail).
Put back the timeouts implemented as part of this hotfix and notice the …

Increase the timeout for MoveGroupCommanders to 15 seconds

---

ow_lander/config/lander_control.yaml
ow_lander/urdf/lander.xacro

Ticket: https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-480
The problem was that the quick solver made europa_test_dem unstable. The quick solver was introduced to reduce the instability between terrain and scoop at the end of guarded_move. Since this problem has already been solved using the kp and kd parameters, we can switch back to the world solver. Here is what I did in these ow_simulator and ow_europa branches: 
- I changed the solver to world in atacama, terminator and test_dem.
- lowered maximum effort and velocity for ant_pan and ant_tilt
- decreased damping for ant_pan and ant_tilt
- Re-tuned PID
- Tested that switching back to world solver doesn't affect sim stability in all three worlds: atacama, terminator, test_dem.
Test 
Required:
- roslaunch ow europa_test_dem.launch …

Oceanwater 480 antenna twitching

---

oceanwaters/doc/setup_dev_env.md

This is just a documentation change, for the corresponding pull request in ow_autonomy: https://github.com/nasa/ow_autonomy/pull/11

Document PLEXIL version needed for installation

---

ow_faults/cfg/Faults.cfg
ow_faults/src/FaultInjector.cpp

Adding Grinder Fault per OW-558
Test
roslaunch project, 
go to dynamic config in rqt and click on either of the grinder faults
observe change in rostopic echo /joint_states

Oceanwater-558 adding grinder fault for arm

---

ow_lander/config/fake_controllers.yaml
ow_lander/config/ros_controllers.yaml
ow_lander/launch/ros_controllers.launch
ow_lander/scripts/activity_full_digging_traj.py
ow_lander/scripts/activity_grind.py
ow_lander/scripts/path_planning_commander.py
ow_lander/scripts/utils.py
ow_lander/srv/DigCircular.srv
ow_lander/srv/DigLinear.srv
ow_lander/srv/Grind.srv

Linked PR: https://github.com/nasa/ow_autonomy/pull/15
Epic Link: https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-518
Linked Issues:
* https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-530
* https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-536
* https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-537
* https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-483 (api enhacements: remove delete_prev_traj)
* https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-526 (remove dependence on trajectory recording)
* Added back the grinder_controller (deactivated by default)
* Created a method that enables switching between two sets of controllers at runtime
* Successfully ported the remaining services to using _JointTrajectoryController_:
- **DigCircular**
- **DigLinear**
- …

Oceanwater 530 enable switching between arm controllers at runtime

---

ow_lander/urdf/stereo_camera_triggered.xacro

I updated IRGCameraSim plugin params based on refined camera estimates documented in the "energy_conversion parameter" section of this page: https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/Visuals

Oceanwater 562 refine camera exposure and energy conversion

---

ow_lander/config/ros_controllers.yaml
ow_lander/launch/ros_controllers.launch

Ticket: https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-559
There are two antenna joints: pan and tilt. Both of them don't need planning and are moved independently. So there's no need to switch to the JointTrajectoryController. In this branch I resumed the JointPositionController only for the antenna. 
Test:
- launch europa_terminator_workspace.launch
- in rqt>Control and Viz>Message Publisher click to expand the /ant_pan_position_controller/command topic. Tick the box. Change rate to 100. In the 'expression' field write float numbers such as: 0.5, 0.8, -0.5, one at a time. Observe antenna reaching the goal positions in Gazebo.
- make sure your ow_autonomy is in the OW-518 branch.
- run ReferenceMission1 : roslaunch ow_autonomy autonomy_node.launch plan:="ReferenceMission1.plx"
- …

Resumed PositionController for ant_pan and tilt

---

ow_lander/config/ros_controllers.yaml

This is mainly a quick refactor of the `ros_controllers.yaml` to avoid setting different PID values for the same joint in different controllers.
* Set pid values once - of the same joint - for all controllers
* Reference only joints that belong to the controller in constraints section
```bash
roslaunch ow atacama_y1a.launch # if this starts then all good
```

set pid values once for all controllers +

---

ow_lander/config/lander.srdf
ow_lander/launch/spawn.launch

This appears to avoid LCP internal errors from ODE on startup, but the arm still starts in slightly different positions each run. A careful investigation is needed to avoid this behavior.

Use new proximal pitch stowed value

---

ow_lander/scripts/activity_full_digging_traj.py

[OCEANWATER-569 | RRTConnect: Unable to sample any valid states for goal tree](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-569)
The changes may not seem like a lot but there is a lot more to it behind the scenes. This avoids the use of the planner to come with a plan to get to the specified pose during the call to **go_to_Z_coordinate**. What this code does instead is asking the planner (the current planner) to generate a plan to the approximate joint values generated by kinematics builtin IK solver. To me this is a workaround but so is https://github.com/nasa/ow_simulator/pull/59. The gain here is it directly addresses the issues with no side effects (yet :roll_eyes:)
>Note: To reproduce the issue that currently exists on **OCEANWATER-518** branch perform dig_circular activity …

Plan using an approximate joint value targets

---

ow_lander/scripts/activity_full_digging_traj.py
ow_lander/scripts/activity_grind.py

* Added a new parameter to go_to_Z_coordinate to indicate that you want to use the approximate solution or not:
- default is to use the approximate solution to address the issue OCEANWATER-569 (Refer to https://github.com/nasa/ow_simulator/pull/60 for more details)
* Pass **False** to retain the previous functionality for the grind activity.
Run [test case 2.8](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST007+-+release-7-0)

Utilize set_pose_target when using the grinder move_group

---

ow_lander/config/ompl_planning.yaml
ow_lander/config/ros_controllers.yaml
ow_lander/scripts/activity_deliver_sample.py

| Jira Ticket 🎟️   | [Oceanwater-544](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-544) |
| EPIC ⚡| [Oceanwater-87](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-87) |
* Changed default planner for arm and limbs move_group to RRTstar
* While testing I noticed some of the PID gains could have been improved, so I adjusted the P gain for yaw pitch and hand
* I did the following tests to verify RRTstar reliability (please keep in mind that grind and deliver_sample were already using RRTstar, so no testing is required for them):
- roslaunch ow_autonomy autonomy_node.launch plan:=ReferenceMission1.plx
- Guarded_move:
rosservice call /arm/guarded_move -- False 1.7 0.3 0.5 0 0 1 0.7
rosservice call /arm/guarded_move -- False …

Oceanwater 544 ensure RRTstar planner is set during arm operations

---

oceanwaters/doc/setup_dev_env.md

| Jira Ticket 🎟️   | [OCEANWATER-590 / add missing ros-melodic-joint-trajectory-controller dependency ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-590) |
| EPIC ⚡| [OCEANWATER-518 / Switch to using JointTrajectoryController ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-518) |
| Github :octocat:  | Closes #72 |
* Add a missing dependency to the setup instructions `ros-melodic-joint-trajectory-controller`
* N/A

Add the missing dependency

---

ow_lander/scripts/activity_guarded_move.py
ow_lander/scripts/ground_detection.py

| Jira Ticket 🎟️ | [OCEANWATER-509 / Guarded Move works for any direction](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-509) |
|:------- |:-------- |
| Jira Ticket 🎟️ | [OCEANWATER-587 / Guarded move works even when simulation has an increased real time update rate](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-509) |
| EPIC ⚡ | [OCEANWATER-87 / Arm Control](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-87) |
* Implemented a mechanism to detect if the arm met the ground (or any obstacle) that works in any direction.
* Added the ability to skip a number of sample to avoid the initial set of outliers before establishing the threshold (renamed to reference vector).
1. Launch the simulation with your favorite world
```bash
roslaunch ow (atacama_y1a.launch | …
```

OCEANWATER-509 guarded move works for any direction

---

ow_faults/cfg/Faults.cfg
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp

*PLEASE NOTE THE BRANCH NAME IS INCORRECT, IT SHOULD BE TICKET 576* 
| Jira Ticket 🎟️   | [Oceanwater-576](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-576) |
| Github :octocat:  | #NA |
*  Added Power faults to rqt list, under dynamic reconfigure 
* added temprary publishers for power fault information as not all power features have been built yet
* on selection of power faults, temporary topics receive fake fault data. 
* TEST 1:
run any roslaunch file, open rqt, click on dynamic reconfigure and see the bottom 3 new power fault options
result:
* TEST 2:
select  thermal power failure and in a termainl enter `rostopic echo temporary/power_fault/temp_increase`. You …

Oceanwaters 576 power faults rqt

---

ow_faults/CMakeLists.txt
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/msg/PowerFaults.msg
ow_faults/src/FaultInjector.cpp

| Jira Ticket 🎟️   | [Oceanwater-580](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-580) |
| EPIC ⚡| [Oceanwater-575](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-575) |
| Github :octocat:  | #68 (pre)  |
* Added new ros msg file for Power Faults and new publisher /power_faults_status. This emulates the similar JPL messages that we build for the arm. JPL doesn't have their own messages for battery however, so we have only a shortlist of what to display, currently only Hardware errors. 
* click on faults for power and in another terminal type `rostopic echo /power_faults_status`. Value in message should be 1
*

Oceanwater 580 power faults messages

---

pull_request_template.md

None
* A minor reformatting to the pull request template in which the epic is moved to the top of the table for the following reasons:
- GitHub renders the first line differently than the rest of the rows
- It is unlikely that a PR would use more than one EPIC, meanwhile a PR can address multiple Jira Tickets
* Use left align for the text of first line  
* Use all caps for the tickets prefix (to be consistent with Jira)
* Refer to #74 for an example on how the template would look like after the restructuring

minor reformatting to the template

---

ow_dynamic_terrain/CMakeLists.txt
ow_ephemeris/CMakeLists.txt
ow_faults/CMakeLists.txt
ow_power_system/CMakeLists.txt

| EPIC ⚡ | [OCEANWATER-577 / Support for ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
| Jira Ticket 🎟️   | [OCEANWATER-578 / Remove strict requirement on OpenCV 3.0 in ow_dynamic_terrain ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-578) |
| Jira Ticket 🎟️   | [OCEANWATER-593 / Don't explicitly set a required C++ standard unless absolutely needed ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-593) |
This is a single iteration at our effort to support **ROS Noetic**, these following changes are necessary and does't break **ROS Melodic** compilation: 
* Use default version of OpenCV on current platform 
* Use catkin default c++ standard
* Make sure the system still successfully compiles against **ROS Melodic**
* …

Use default version of OpenCV on current platform + Use catkin default c++ standard

---

ow_gazebo_plugins/CMakeLists.txt

| Jira Ticket 🎟️   | [Oceanwater-592](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-592) |
| EPIC ⚡| [Oceanwater-577](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
* Removed Qt requirement from ow_gazebo_plugins as it is not being used.
* compile the workspace

Oceanwater 592 remove qt4

---

ow_dynamic_terrain/CMakeLists.txt

| EPIC ⚡| [Oceanwater-577 / Support for ROS Noetic ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
| :---------- | :---------- |
| Jira Ticket 🎟️   | [Oceanwater-597 / Resolve compile errors stemming from ignite library against ros noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-597) |
* Require C++17 for ow_dynamic_terrain on Noetic only
* Using a clean build, make sure the project still compiles with no issues towards **ros-melodic**
* If you happen to have an Ubuntu 20.04 with **ros-noetic** installed, verify that **ow_dynamic_terrain** package can compile successfully.

Require C++17 for ow_dynamic_terrain on Noetic

---

ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp

| Jira Ticket 🎟️   | [Oceanwater-603](urlhttps://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-603 |
| Github :octocat:  | depends on #82  |
* added power faults to bitmask for System Faults
* launch any ow launch file
* rostopic echo /system_faults_status
* go into rqt dynamic reconfigure and check the power faults (or any others)
* observe the value change on rostopic echo

Oceanwater 603 power faults bitmask

---

ow_lander/CMakeLists.txt
ow_lander/scripts/path_planning_commander.py
ow_lander/srv/Stop.srv

Add an Arm Stop command
| EPIC ⚡| [OCEANWATER-518 / Switch to using effort_controllers/JointTrajectoryController](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-518) |
| :---------- | :---------- |
| Jira Ticket 🎟️   | [OCEANWATER-604 / Implement Stow/Unstow using TrajectoryAsyncExecuter](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-604) |
| Github :octocat:  |  related to #81  |
* Implement **Stow** / **Unstow** arm services using TrajectoryAsyncExecuter
* Add an arm stop command
Launch the simulation
```bash
```
Execute either **Stow** or **Unstow** through RQT Service Call or using the commands 
```bash
rosservice call /arm/unstow 
rosservice call /arm/stow 
```
To stop the arm at any point (applies only to **Stow**, **Unstow** activities …

Implement Stow/Unstow using trajectory async executer + Add an arm stop command

---

oceanwaters/doc/setup_dev_env.md

* Plexil install instructions only.  This update is urgent because the current instructions build Plexil in a way that won't work with Release 7.
* Delete your existing Plexil installation ($PLEXIL_HOME directory)
* Follow the instructions in the README to re-install/build Plexil.
* Rebuild ow_autonomy:
```
rm -rf <ow_workspace>/build/ow_autonomy
catkin build ow_autonomy
```
* Run a bit of ReferenceMission1.  Just getting to the antenna pan/tilt at the start is enough.
`roslaunch ow_autonomy autonomy_node.launch plan:=ReferenceMission1.plx`

updated Plexil install instructions

---

ow_faults/CMakeLists.txt
ow_faults/cfg/Faults.cfg
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/msg/ArmFaults.msg
ow_faults/msg/PTFaults.msg
ow_faults/msg/PowerFaults.msg
ow_faults/msg/SystemFaults.msg
ow_faults/src/FaultInjector.cpp

| Jira Ticket 🎟️   | [Oceanwater-605](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-605) |
| Github :octocat:  | na |
* New pant and tilt faults in Rqt
* on select, populate JPL messages for pan/tilt message in /pt_faults_status
* open any roslaunch
* go to rqt, dynamic recongfigure, and select from either a pan or tilt fault
* rosoptic echo /pt_faults_status and see the value update to 1 (hardware fault)

Oceanwater 605 antennae faults in rqt

---

ow_lander/urdf/lander.xacro

| EPIC ⚡| [OCEANWATER-614 / Implement a force torque sensor for the lander arm ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-614) |
| Jira Ticket 🎟️   | [OCEANWATER-615 / Introduce a force torque sensor for the dist_patch joint ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-615) |
* Introduced a force torque sensor for the dist_patch joint
```bash
roslaunch ow (atacma_y1a.launch | europa_terminator_workspace.launch)
```
* While the simulation running open another terminal and use rostopic to listen to the **ft_sensor_dist_pitch** topic
```bash
rostopic echo /ft_sensor_dist_pitch
```
You should see a stream of **WrenchStamped** messages with relatively stable values for force and torque. …

add an ft sensor to the dist_patch joint

---

ow_lander/scripts/ground_detection.py

| EPIC ⚡| [OCEANWATER-614 / Implement a force torque sensor for the lander arm ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-614) |
| Jira Ticket 🎟️   | [OCEANWATER-616 / Implement guarded move using readings of the ft sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-616) |
* Implement guarded move using readings of the ft sensor
* Removed the old method
1. Launch the simulation
```bash
roslaunch ow (atacma_y1a.launch | europa_terminator_workspace.launch)
```
2. While the simulation running invoke guarded move with varying set of valid arguments in the same session.
```bash
rosservice call /arm/guarded_move -- True 0 0 0 0 0 0 0
rosservice call /arm/guarded_move -- False 1.7 0.3 0.5 0 0 1 0.7
rosservice …
```

Implement guarded move using readings of the force torque sensor

---

ow_ephemeris/CMakeLists.txt
ow_ephemeris/config/europa.yaml

| EPIC ⚡| N/A |
| :---------- | :---------- |
| Jira Ticket 🎟️   | [OCEANWATER-627 / Address the missing jup310.bsp file ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-627) |
| Github :octocat:  | related #105 |
* Replaced `jup310.bsp` with the newer `jup365.bsp` file
* Run a clean catkin build, the new bsp file should be downloaded instead of the old on
* Once build is successful run the simulation and make sure the simulation condition are the same before the hotfix

Replace jup310.bsp with the newer jup365.bsp

---

ow_power_system/README.md
ow_power_system/src/power_system_node.cpp

| Jira Ticket 🎟️   | [Oceanwater-613](https://babelfish.arc.nasa.gov/jira/secure/RapidBoard.jspa?rapidView=168&projectKey=OCEANWATER&view=detail&selectedIssue=OCEANWATER-613) |
| DoD: One of the output parameters of the GSAP prognostics factory is temperature. It needs to be converted to a ROS topic that can be subscribed to by users for fault injection. |
| EPIC ⚡| [Oceanwater-84](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-84) |
* Identified and helped fix a GSAP issue that previously made temperature inaccessible
* Identified and helped fix a GSAP bug that caused an under-prediction of temperature values 
* Added Temperature calculation and extraction from state matrix
* Created rostopic to publish value to power system node
* Updated README to …

OCEANWATER-613_Add_Temperature_as_a_ROS_Topic

---

ow/launch/common.launch
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp

| Jira Ticket 🎟️   | [Oceanwater-607](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-607) |
| Github :octocat:  | ow_autonomy [PR](https://github.com/nasa/ow_autonomy/pull/29)  |
IMPORTANT! To run this, you will need to also pull the ow_autonomy [pr](https://github.com/nasa/ow_autonomy/pull/29) of the same name. 
* antennae faults now cause antennae movement to be halted depending on pan or tilt
* remapping pan and tilt topics from rviz and autonomy nodes
* set original topics to /_original
* 'NEW' topics:
** /ant_pan_position_controller/command
** /ant_tilt_position_controller/command
TEST REMAPPING
* roslaunch any launch file
** to see autonomy remapping, you will …

OCEANWATER 607  Pan/Tilt Faults Halt Antennae Movement 

---

ow_lander/urdf/lander.xacro

| EPIC ⚡| [OCEANWATER-614 / Implement a force torque sensor for the lander arm ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-614) |
| Jira Ticket 🎟️   | [OCEANWATER-617 / Introduce sufficient noise to model a realistic sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-617) |
* Set sensor update rate to 250 Hz
* set sensor gaussian noise level to 0.2
- Noise value is based on generated noise profile of the [Barret FT sensor](https://web.barrett.com/files/Low-Profile_Force-Torque_Sensor_FT-02-2011.pdf)
- See table listed below for comparison of real signal vs simulated  
| Real | Simulated |
| :----------: | :----------: |
|![image](https://user-images.githubusercontent.com/606033/112533125-daaec700-8d66-11eb- …

OCEANWATER-617: Set appropriate sensor update rate and noise

---

ow_faults/README.md
ow_faults/cfg/Faults.cfg
ow_faults/src/FaultInjector.cpp

| Jira Ticket 🎟️   | [Oceanwater-624](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-630) |
| Github :octocat:  | https://github.com/nasa/ow_autonomy/pull/30 |
*** requires ow_autonomy to be updated to the linked PR
*renaming force torque to effort
* roslaunch any
* ropstopic echo system_faults_status
* select any faults from rqt
* see output still in rostopic.

Oceanwater 630 rename ft faults

---

ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp
ow_lander/scripts/path_planning_commander.py
ow_power_system/include/power_system_node.h
ow_power_system/src/power_system_node.cpp

| Jira Ticket 🎟️   | [Oceanwater-660](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-660) |
| EPIC ⚡| [Oceanwater-551](urlhttps://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-551) |
| Github :octocat:  | (pre) #98, (sister-in autonomy) https://github.com/nasa/ow_autonomy/pull/35  |
NOTE: Must also pull from OW autonomy PR (linked above)
* renaming and reorganizing names for clarity
* anything remapped stays as is
* `/faults/jpl/` prefix for jpl message topics
* `/faults/trigger` prefix for topics that trigger other node's to take action (ie. power)
* test build

Oceanwater 660 rename faults vars

---

ow_lander/scripts/deliver_action_server.py
ow_lander/scripts/dig_circular_action_server.py
ow_lander/scripts/dig_linear_action_server.py
ow_lander/scripts/grind_action_server.py
ow_lander/scripts/guarded_move_action_server.py
ow_lander/scripts/mechanical_power_arm.py
ow_lander/scripts/path_planning_commander.py
ow_lander/scripts/stow_action_server.py
ow_lander/scripts/trajectory_async_execution.py
ow_lander/scripts/unstow_action_server.py

| Jira Ticket 🎟️   | [Oceanwater-553](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-553) |
| Github :octocat:  | #66 (parent) |
* goal: updating arm actions s.t. a faults trigger will halt arm movement
* updating trajectory async executor to keep track of arm fault boolean 
* updating arm actions to listen to faults
* stow
* unstow
* Move guarded
* grind
* dig circular
* dig linear
* deliver sample
* `roslaunch ow europa_terminator_workspace.launch`
* in new terminal, try any of the following actions
python unstow_action_client.py
python stow_action_client.py
python guarded_move_action_client.py
python grind_action_client.py
python dig_linear_action_client.py …

stopping all arm actions

---

ow_power_system/include/power_system_node.h
ow_power_system/src/power_system_node.cpp

| EPIC ⚡| [OCEANWATER-84 / Power System Modelling](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-84) |
| Jira Ticket 🎟️  | [OCEANWATER-652 / Remove the strong dependency of PowerSystemNode on joint_states topic ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-652) |
| Jira Ticket 🎟️  | [OCEANWATER-673 / When power faults are injected the publish rate of power value is increased ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-673) |
* Decouple the processing of power values from the joint_states callback. This was critical for the following factors:
- Prognoser takes too much time to process data and thus is not able to keep up
- This entails that not all power values were actually being processed
- Also, …

Decouple dependency of PowerNode on joint_states topic +

---

ow_lander/scripts/grind_action_server.py

| Jira Ticket 🎟️   | [Oceanwater-XXX](url) |
| EPIC ⚡| [Oceanwater-XXX](url) |
* Change back controller in the event of fault. 
* Test 6.4 . Re-do test 6.4 to see if it works.

 switching back controllers in grind in the event of fault

---

ow_lander/scripts/action_deliver_sample.py
ow_lander/scripts/action_dig_circular.py
ow_lander/scripts/action_dig_linear.py
ow_lander/scripts/action_grind.py
ow_lander/scripts/action_guarded_move.py
ow_lander/scripts/activity_deliver_sample.py
ow_lander/scripts/activity_full_digging_traj.py
ow_lander/scripts/activity_grind.py
ow_lander/scripts/activity_guarded_move.py
ow_lander/scripts/path_planning_commander.py
ow_lander/scripts/stow_action_server.py
ow_lander/scripts/unstow_action_server.py

| EPIC ⚡| [OCEANWATER-577 / Support for ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
| Jira Ticket 🎟️   | [OCEANWATER-704 / MoveIt Commander throws an exception for arm ros actions interface under Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-704) |
* The goal for all MoveIt MoveGroup planning requests is explicitly set in a separate call
* All plan requests expects a tuple of 4 as an answer to the return request    
> Note: You need to be on Ubuntu 20.04 with ROS Noetic installed to test this
* Run through tests [2](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST008+-+release-8-0#OWTEST008release80-2.Samplecollection:planningandexecution) and …

Oceanwater 704 moveit commander throws an exception for arm ros actions interface under noetic

---

ow/launch/common.launch
ow_faults/CMakeLists.txt
ow_faults/cfg/Faults.cfg
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/msg/CamFaults.msg
ow_faults/src/FaultInjector.cpp

| EPIC ⚡| [OCEANWATER-698](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-698) |
| Jira Ticket 🎟️   | [OCEANWATER-551](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-551) |
* New JPL msg CamFaults.msg
* new rqt option for camera trigger fault
* new topic for jpl messages
* * /faults/camera_fault_status
* new function to handle all publishing to system faults status
* remapped /StereoCamera/left/image_trigger with prefix /_original
* On camera trigger fault, camera trigger does not fire and publishes error to cam faults status and system faults status.
`roslaunch ow atacama_y1a.launch 
`
TEST REMAPPING
* `rostopic info /_original/StereoCamera/left/image_trigger`
** observe that it is subbed by the Faults node
* …

Oceanwater 698 cam trigger fault

---

ow_lander/config/joint_limits.yaml

| EPIC ⚡| [OCEANWATER-577 / Support for ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
| Jira Ticket 🎟️   | [OCEANWATER-705 / Arm moves very slow under ROS Melodic and Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-705)) |
* disable velocity limits on all joints
```bash
```
* Run any arm operation
```bash
rosservice call /arm/stow
rosservice call /arm/unstow
```
* Arm should execute the operation normally as before

disable velocity limits on joints

---

ow_lander/config/joint_limits.yaml

| EPIC ⚡| [OCEANWATER-577 / Support for ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
| Jira Ticket 🎟️   | [OCEANWATER-705 / Arm moves very slow under ROS Melodic and Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-705)) |
| Github :octocat:  | #136  |
**Problem Statement:** After some recent updates made to ROS Moveit (Melodic/Noetic), the lander arm started to move very slow. This issue was probably caused by a feature in MoveIt that OceanWATERS was making use of but it wasn't functional. The feature in question basically gives users the ability to limit the speed at which joints can move. 
**Solution:** Disable velocity limits on all joints
```bash
```
* Run …

HOTFIX: Disable velocity limits on all joints

---

ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp

| EPIC ⚡| [OCEANWATER-706](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-706) |
| Jira Ticket 🎟️   | [OCEANWATER-551](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-551)) |
*  updating where cam faults get published such that when selected in rqt, messages are published. 
*  see tests from #129

Oceanwater 706 update camera fault

---

ow_lander/urdf/lander.xacro

| EPIC ⚡| [OCEANWATER-680 / Sample Acquisition](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| Jira Ticket 🎟️   | [OCEANWATER-707 / Rigid bodies are prone to fall through the scoop](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-707) |
| Github :octocat:  | NA |
* Removed the l_scoop.stl as the mesh collider for the scoop and replaced it with a series of box colliders that approximate the scoop's shape.
Image is from Blender, which was used to design the new collision model. Note that in this image planes are being used, but since plane collisions in Gazebo only work as infinite planes, the final collision model was built with thin walled boxes placed in the same poses.
https://user-images.githubusercontent.com/17039973/122287481-38f2c …

Oceanwater 707 scoop collider improvement

---

ow_lander/config/joint_limits.yaml

| EPIC ⚡| N/A |
| Jira Ticket 🎟️   | N/A |
| Github :octocat:  | #138  |
This PR reverts the changes made by #138 due to the side effects observed with that PR.
As a result any user who upgraded their moveit installation to 1.0.8 will experience the slow arm movement.
N/A

re-impose velocity limits on joints

---

ow_lander/config/joint_limits.yaml
ow_lander/scripts/action_guarded_move.py

| EPIC ⚡| [OCEANWATER-577 / Support for ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
| Jira Ticket 🎟️   | [OCEANWATER-705 / Arm moves very slow under ROS Melodic and Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-705) |
| Jira Ticket 🎟️   | [OCEANWATER-715 / Fix Velocity Limit issue with Moveit](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-715) |
| Github :octocat:  | #136, #147  |
**Problem Statement:** After some recent updates made to ROS Moveit (Melodic/Noetic), the lander arm started to move very slow. This issue is caused by recent changes made to **MoveIt** (since v1.0.8) that changed the initial values of `default_velocity_scaling_factor` and `default_acceleration_scaling_factor` from 1.0 to 0.1. …

HOTFIX: Address the slow movement of arm after recent moveit update

---

ow_lander/launch/move_group.launch

| EPIC ⚡| [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
) |
| Jira Ticket 🎟️   | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX)) |
* Removes planning (RRT) output from the terminal. 
* Test all the actions and main terminal window should not display any planning output

remove RRT planning output from terminal

---

oceanwaters/doc/setup_dev_env.md

The previous instructions incorrectly referred to a tag as a branch.  The revision also simplifies this section and reformats the text to read better in an ASCII editor.
No test is needed.

Fixed GSAP install instructions

---

ow_sim_tests/test/arm_check.py
ow_sim_tests/test/arm_check.test

| EPIC ⚡| [OCEANWATER-684 / Automated Build & Testing ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-684) |
| Jira Ticket 🎟️   | [OCEANWATER-738 / full automation of lander arm release test case 2](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-738) |
| Github :octocat:  | #149 |
* Fully automated test case 2 of [OceanWATERS release tests](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST008+-+release-8-0?searchId=O143IYLN6)
* To test arm operation run the following command:
```bash
rostest ow_sim_tests arm_check.test
```
This should run successfully and print a summary of 10 tests. If there are no issues in the simulation/lander operation, then all tests should show as succeeded. If there is any issue in the behavior of …

Oceanwater 738 full automation of lander release test case 2

---

ow_sim_tests/test/ft_sensor.test
ow_sim_tests/test/ft_sensor_check.py
ow_sim_tests/test/test_minimum_fps.py

| EPIC ⚡ | [OCEANWATER-684 / Test Automation](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-684) |
| Jira Ticket 🎟️ | [OCEANWATER-754 / Automate Force/Torque Sensor Test Procedures](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-754) |
* Automated Main [Test Procedure for F/T Sensor]((https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST009+-+release-9-0#OWTEST009release90-7.Force/TorqueSensor)
- ~Checks for GuardedMove are not included here .. it will be better to move GuardedMove checks to a separate test case~
* After building the project use `rostest ow_sim_tests ft_sensor.test` to launch the test, expected output:

Oceanwater 754 automate ft sensor test procedures

---

ow/package.xml
ow_bag_recorder/package.xml
ow_dynamic_terrain/package.xml
ow_ephemeris/package.xml
ow_faults/package.xml
ow_gazebo_plugins/package.xml
ow_sim_tests/package.xml
ow_testbed/package.xml

| Jira Ticket 🎟️ | [OCEANWATER-760](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-760) |
* Added proper license tag too all package.xml files
No testing required, but please verify that the tag is correct and that I got all package.xml files that needed it.

OCEANWATER 760 - Gave every package.xml file the proper license tag

---

ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp
ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp

| EPIC ⚡ | [OCEANWATER-717](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-717) |
| Jira Ticket 🎟️ | [OCEANWATER-721](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-721) |
| Github :octocat:  | epic #140  |
* moved antenna faults detection ti detector node 
* roslaunch any launch file
* in a new terminal  `rostopic echo /faults/pt_faults_status`
* go to rqt and from Control and Viz tab update value to any value for 'command' for pan to 1
* go to rqt dynamic reconfigure and select either pan or tilt fault (respective to the topic you're observing)
* Control+Viz, update value to 2
* observe fault value of 1 in the rostopic echo terminal. 
* repeat for tilt

OCEANWATER 721 Detect Ant Faults

---

ow_lander/CMakeLists.txt
ow_lander/launch/spawn.launch
ow_lander/materials/scripts/ow_lander.frag
ow_lander/materials/scripts/ow_lander.material
ow_lander/scripts/lander_service_server.py
ow_lander/srv/Light.srv

| Jira Ticket 🎟️ | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-759) |
* Added ability to set light intensity from 0.0 to 1.0
* Check out the same branch in ow_europa
* rostopic pub -1 /_original/ant_tilt_position_controller/command std_msgs/Float64 1.3
* rostopic pub -1 /_original/ant_pan_position_controller/command std_msgs/Float64 1.5
* rosservice call /lander/light    Use tab completion and set to "name: 'left' intensity: 0.0"
* rosservice call /lander/light    Use tab completion and set to "name: 'right' intensity: 0.0"
* rosservice call /lander/light    Use tab completion and set to "name: 'left' intensity: 1.0"
* rosservice call /lander/light    Use tab completion and set to "name: 'right' intensity: 1.0"
It's difficult to …

Oceanwater 759 spotlight control

---

ow/launch/common.launch
ow_faults/CMakeLists.txt
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/include/ow_faults/JointsFaults.h
ow_faults/src/FaultInjector.cpp
ow_faults/src/JointsFaults.cpp
ow_lander/urdf/lander.xacro

| EPIC ⚡ | [OCEANWATER-551 / OW Faults Injection](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-551) |
| Jira Ticket 🎟️ | [OCEANWATER-785 / Prototype antenna faults by locking joints](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-785) |
* Implemented a **JointsFaults** module that utilizes joint limits to lock the joints at their current position
- Changed antenna joint types from **continuous** to **revolute** joint types (required to impose joint limits)
* Currently only applied to _j_ant_pan_ and _j_ant_tilt_ joints but the concept can be expanded to other joints
> Note: this is a quick prototype to get some feedback ad may not be eventually merged into **melodic-devel**
```bash …
```

OCEANWATER-785: prototype antenna faults by locking joints

---

ow_faults/include/ow_faults/JointsFaults.h
ow_faults/src/FaultInjector.cpp
ow_faults/src/JointsFaults.cpp
ow_lander/urdf/lander.xacro

| EPIC ⚡ | [OCEANWATER-551 / OW Faults Injection](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-551) |
| Jira Ticket 🎟️ | [OCEANWATER-791 / prototype arm joint faults utilizing joints locking](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-791) |
| Github :octocat:  | related: #170 |
* Arm Fault Inject through joint locking
* Switched from using _Joint Upper/Lower Limits_ to lock the joint to using _Joint Friction_
* Disabled the check for arm_fault such that no fault injection is placed through the arm action servers
```bash
```
* Verify that you can freely control the arm
```bash
rosservice call /arm/unstow
```
* Enable a fault on one or more of the arm joints:
```bash
rosrun …
```

OCEANWATER-791: prototype arm faulting utilizing joints locking

---

ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp
ow_faults_injection/src/FaultInjector.cpp

| EPIC ⚡ | [OCEANWATER-718 / detection epic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-718) |
| Jira Ticket 🎟️ | N/A |
| Github :octocat:  | #140 |
* Check the return value of findJointIndex within isFlagSet before using the returned index
```bash
```
Check that the FaultDetector node launches successfully and doesn't crash

fixed the issue causing the FaultDetector node to crash

---

ow_lander/scripts/arm_action_servers.py

| Jira Ticket 🎟️ | [OCEANWATER-832](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-832) |
* Removed unused code
* roslaunch ow_plexil ow_exec.launch plan:=ReferenceMission1.plx
* Without this change you should see 3 instances of "Grind finished in state ABORTED"
* With this change you should instead see "Grind finished in state SUCCEEDED"

Removed legacy code that was causing grind failures.

---

ow_lander/scripts/all_action_trajectories.py
ow_lander/scripts/arm_action_servers.py

| EPIC ⚡ | [ N/A ] |
| Jira Ticket 🎟️ | [OCEANWATER-833 / update moveit syntax for noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-833) |
| Jira Ticket 🎟️ | [OCEANWATER-834 / Arm actions fails to perform dig motions on ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-834) |
| Jira Ticket 🎟️ | [OCEANWATER-835 / Dig Circular fails to perform when using non parallel move](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-835) |
| Github :octocat:  | builds on #187 |
* All changes from #187 
* Address bug arm actions fails to perform dig motions on ROS Noetic
* Address bug "Dig Circular" fails to perform when using non parallel move
* Code cleanup:
- Remove unused parameters of function `go_to_Z_coordinate_dig_circular`
- …

OCEANWATER-/833/834/835: address multiple issues within the ros action interface of the lander arm on ROS Noetic

---

ow_dynamic_terrain/models/europa_terrain/model.sdf
ow_dynamic_terrain/models/ogre_terrain/model.sdf
ow_dynamic_terrain/models/small_box/model.sdf

| EPIC ⚡ | [N/A] |
| Jira Ticket 🎟️ | [OCEANWATER-845 / Address ow_dynamic_terrain sdf warnings](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-845) |
* Upgrade ow_dynamic_terrain models SDF version to 1.7
* Remove frame attribute from pose
* Launch the simulation and monitor the log 
```bash
roslaunch ow_dynamic_terrain europa.launch
```
* Verify that all SDF warnings and errors are gone

OCEANWATER-845: Upgrade sdf version to 1.7 and remove frame attribute from pose

---

ow_regolith/src/RegolithSpawner.cpp

| Jira Ticket 🎟️ | [OCEANWATER-848 / Resolve the intermittent Gazebo crashes under ROS Noetic](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-848) |
* Replace the usage of negative value to disable the time de-activation of wrench force in the ow_regolith plugin with a long ROS duration (1 year). This should avoid the intermittent crashes that were observed in Gazebo.
>Note: After implementing this fix I could not get Gazebo to crash. But please note that this fix probably only addresses part of the problem. If issue is still observed please report it.
* Source **OceanWATERS** environment and launch the simulation:
```bash
roslaunch ow atacama_y1a.launch use_rviz:=false rqt_gui:=false
```
* In another …

HOTFIX/OceanWATER-848: Choose a long ros duration (1 year), to delay the automatic disable of wrench force within ow_regolith module

---

ow_dynamic_terrain/src/DynamicTerrainModel.cpp

| Jira Ticket 🎟️ | [OCEANWATER-819 / Suppress or prevent "ODE Message 3: LCP internal error"](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-819) |
* This hotfix simply suppresses the LCP error emitted by ODE from being printed to the console
* Source **OceanWATERS** environment and launch the simulation:
```bash
roslaunch ow atacama_y1a.launch use_rviz:=false rqt_gui:=false
```
* In another terminal, source **OceanWATERS** environment and run the `ReferenceMission1.plx` plan:
```bash
roslaunch ow_plexil ow_exec.launch plan:=ReferenceMission1.plx
```
* Verify that the message `ODE Message 3: LCP internal error, s <= 0 (s=-0.0000e+00)` no longer appears on any of the two cases:
- When the arm collides with …

HOTFIX/OceanWATERS-819: Suppress the LCP error message

---

ow_lander/urdf/stereo_camera_triggered.xacro

| Jira Ticket 🎟️ | [OCEANWATER-847 / Resolve the warning message "Could not fill color channel of the point cloud, unsupported encoding 'rgb16'"](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-847) |
* Update the output format of the stereo camera to match the formats supported by stereo_image_proc node
* The generate point cloud now correctly displays colors:
| Before Fix | After Fix |
| :------------: | :------------: |
| ![image](https://user-images.githubusercontent.com/606033/144503540-c516087e-fbd6-4c8c-9381-2780edf842cb.png) | ![image](https://user-images.githubusercontent.com/606033/144502369-392878f2-f3d9-48d1-91e3-807794ba3c35.png) |
| ![image](https://user-images.githubusercontent.com/606033/1445 …

HOTFIX/OceanWATERS-847: Resolve warning could not fill color channel of point cloud

---

ow_regolith/CMakeLists.txt
ow_regolith/README.md
ow_regolith/include/RegolithSpawner.h
ow_regolith/package.xml
ow_regolith/src/RegolithSpawner.cpp
ow_regolith/srv/RemoveAllRegolith.srv
ow_regolith/srv/SpawnRegolithInScoop.srv

| EPIC ⚡ | [OCEANWATER-680](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| Jira Ticket 🎟️ | [OCEANWATER-840](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-840) |
* Added `ow_regolith/spawn_regolith_in_scoop` and `/ow_regolith/remove_all_regolith`.
`ow_regolith/spawn_regolith_in_scoop` will spawn a single regolith model just above the tip of the scoop. Unlike when spawning is triggered by terrain modification, there will be no psuedo force applied to the model when this service is called.
`ow_regolith/remove_all_regolith` will delete all regolith models from the simulation.
Both services together provide a minimal interface into regolith_node that can be helpful for both debugging purposes and some specific …

OceanWATER-840 Added spawn regolith and remove regolith services

---

ow_power_system/include/power_system_node.h
ow_power_system/src/power_system_node.cpp

| Jira Ticket 🎟️ | [OCEANWATER-857 / Mechanical Power is not an accumulate of all joints](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-857) |
* Accumlate the mechanical power of all joints
* Use absolute values for velocity when computing mech power
* Use `ros::param::getCached` to read fault flag value to speed up the check
* Verify that the change resolves issues found during [OceanWATERS Release 9 System Tests for Power System Node](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST-009-8+Power+System)

HOTFIX/OceanWATER-857: Mechanical Power is not an accumulate of all joints

---

ow_regolith/include/RegolithSpawner.h
ow_regolith/src/RegolithSpawner.cpp

| EPIC ⚡ | n/a  |
| Jira Ticket 🎟️ | [OCEANWATER-852](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-852) |
**ow_regolith** now requires that the scoop end-effector's bottom faces downward before regolith will spawn in the scoop as the result of a visual terrain modification. This will ensure deep grinds won't result in regolith.
In interest of saving time: @Samahu feel free to just review code. @mikedalal feel free to just perform the test.
1. Launch `atacama_y1a`
2. Call a grind action, and set the depth parameter to at least `0.15`, which will cause a deep enough grind to modify the visual terrain. Here's an example command that keeps other variables default 
```./grind_action_client.py 1.65 0.0 0.15```
3. Open the Models …

OCEANWATER 852 - Fix regolith spawning during a grind

---

ow_lander/launch/spawn.launch

| Jira Ticket 🎟️ | [OCEANWATER-888](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-888) |
* Removed a joint_state_publisher from spawn.launch. It was unnecessary because /_original/joint_states is already being published by /gazebo due to specifying a joint_state_controller in ros_controllers.launch. The joints published by joint_state_controller are in alphabetical order while joint_state_publisher publishes them in the order they appear in the urdf, which is why something like `/joint_states/position[0]` shows different values from each of these programs.
* Use `rostopic info` to ensure that `/joint_states` and `/_original/joint_states` each have only one publisher.
* Run your favorite plexil plan to see if the sim still works as expected.

Removed extraneous joint_state_publisher.

---

ow_lander/scripts/antenna_pan_tilt_action_server.py
ow_lander/scripts/arm_action_servers.py

| Jira Ticket 🎟️ | [OCEANWATER-898](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-898) |
Fixes a bug whereby any of the **ow_lander** action servers could fail if they were initialized while an action client was already waiting for them to exist. 
Each action server was passing a member function to SimpleActionClient, which spun-off a thread that could call that member function before the action server's `__init__` function finished initializing the remainder of the action server's member variables. This appears to only occur if there was an action client already waiting for the action server to exist.
* SimpleActionClient is now called at the very end of each action server's `__init__` function, ensuring …

Oceanwater 898 Fix ow_lander actions failing if called too early

---

ow_regolith/include/PersistentServiceClient.h
ow_regolith/include/RegolithSpawner.h
ow_regolith/include/ServiceClientFacade.h
ow_regolith/src/RegolithSpawner.cpp
ow_regolith/src/regolith_node.cpp
ow_regolith/src/sdf_utility.cpp

| EPIC ⚡ | [OCEANWATER-680](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| Jira Ticket 🎟️ | [OCEANWATER-843](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-843) |
* Persistent service clients are implemented as a facade pattern that encapsulates auto-reconnect logic.
* Results in improved performance when calling commonly called services.
* Addressed a miss-use of `std::unique_ptr`. Now using `std::shared_ptr` to support the new persistent service clients.
* Numerous code clean-ups, including:
* ALL_CAPS constant names
* Node parameters now grabbed in `initialize()` function allowing handling of parameter errors.
Similar to past tests of this node. Everything should work the same.
1. Launch `atacama_y1a` …

Oceanwater 843 Reinstate persistent service clients and code clean-up

---

ow_ephemeris/CMakeLists.txt

| Jira Ticket 🎟️ | [OCEANWATER-897 / Replace deprecated sat427 with sat441](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-897) |
* Replace deprecated sat427 with sat441
* Launch the simulation before applying the hotfix take a screenshot of where Jupiter planet appears relative to the lander
* Checkout the hotfix branch
* Delete the `sat427.bsp` file from `src/ow_simulator/ow_ephemeris/data/`
* Verify that the workspace compiles successfully
* Launch the simulation and verify that Jupiter  appears in the same position relatives to the lander

HOTFIX/OCEANWATER-897: Replace deprecated sat427 with sat441

---

ow_lander/config/ompl_planning.yaml
ow_lander/launch/spawn.launch

| EPIC ⚡ | [OCEANWATER-901](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
| Jira Ticket 🎟️ | [OCEANWATER-901](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-901) |
* Changing Planner from RRT* to RRT-Connect. 
* With these changes rviz playback is not an issue. 
* roslaunch ow atacama_y1a.launch 
test all the action clients
./unstow_action_client.py 
./grind_action_client.py 
./dig_circular_action_client.py 
./dig_linear_action_client.py 
./deliver_action_client.py

Oceanwater 901 bypass rviz playback arm action

---

ow_faults_injection/include/ow_faults_injection/FaultInjector.h
ow_faults_injection/src/FaultInjector.cpp

| Jira Ticket 🎟️ | [OCEANWATER-919](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-919) |
| Github :octocat:  | closes #227 |
* Removed the code that was setting the position of locked joints to zeros
| On Arm Fault (noetic-devel) | On Arm Fault (this branch) |
| :-----------------------------------: | :---------------------------------: |
| ![joints_fault](https://user-images.githubusercontent.com/606033/160684605-e8eb0796-7128-4832-a91f-05075da0c91e.png) | ![joint_same](https://user-images.githubusercontent.com/606033/160684746-c3586b13-693d-435d-8a2a-e0e1ff1da598.png) |
* Confirm that before this change that when a fault is applied to a specific joint it value is set to zero
- as reported in #227
* After checking out this branch …

OCEANWATER-919: Don't zero joint values when arm faults are injected

---

ow_lander/scripts/arm_action_servers.py
ow_lander/scripts/deliver_action_client.py
ow_lander/scripts/dig_circular_action_client.py
ow_lander/scripts/dig_linear_action_client.py
ow_lander/scripts/discard_action_client.py
ow_lander/scripts/grind_action_client.py
ow_lander/scripts/guarded_move_action_client.py
ow_lander/scripts/stow_action_client.py
ow_lander/scripts/trajectory_async_execution.py
ow_lander/scripts/unstow_action_client.py

| Jira Ticket 🎟️ | [OCEANWATER-923](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-923) |
* Detects if the arm actions have been stopped by the stop action server and reports the current actions as failed. 
In 3 seperate terminals:
1. roslaunch ow atacama_y1a.launch
2. launch any of the action files:
-   ./unstow_action_client.py
-   you can check for all other action clients like dig_circular, dig_linear etc...
3. Stop the motion during any phase of the arm movement.
./stop_action_client.py
The terminal should report that the action failed and was stopped.

 OCEANWATER-923 actions report failed when stopped by stop action client

---

ow_faults_injection/include/ow_faults_injection/FaultInjector.h
ow_faults_injection/src/FaultInjector.cpp

| Jira Ticket 🎟️ | [OCEANWATER-919](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-919) |
| Github :octocat:  | closes #227, related #229 |
* Removed the code that was setting the position of locked joints to zeros
| On Arm Fault (noetic-devel) | On Arm Fault (this branch) |
| :-----------------------------------: | :---------------------------------: |
| ![joints_fault](https://user-images.githubusercontent.com/606033/160684605-e8eb0796-7128-4832-a91f-05075da0c91e.png) | ![joint_same](https://user-images.githubusercontent.com/606033/160684746-c3586b13-693d-435d-8a2a-e0e1ff1da598.png) |
* Confirm that before this change that when a fault is applied to a specific joint it value is set to zero
- as reported in #227
* After checking out …

HOTFIX/OCEANWATER-919: Remove the reset of joint values when arm fault are injected

---

ow_lander/launch/spawn.launch

| Jira Ticket 🎟️ | [OCEANWATER-930 / parts of ros services no longer work](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-930) |
| Github :octocat:  | #226 |
* The PR #226 introduced an issue that hindered the execution of certain commands of the ros services interface
* This PR reset the flag _allow_trajectory_execution_ back to **true**
Run the following system tests:
* https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/CopyOfOW-TEST-009-3+Sample+Collection
* https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/CopyOfOW-TEST-009-4+ROS+Actions

BUGFIX/OCEANWATER-930: parts of ros services no longer work

---

oceanwaters/doc/setup_dev_env.md

This is just a documentation update, advising users to incorporate the fix described in https://github.com/nasa/ow_simulator/wiki/Troubleshooting#ignition-transport-failure-on-vpn  when they first install Gazebo.

Gazebo install instructions include Ignition Transport fix

---

ow_lander/scripts/action_trajectories.py
ow_sim_tests/test/terrain_interaction.py

| Jira Ticket 🎟️ | [OCEANWATER-932](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-932) |
* Changed default planner for discard and deliver to RRT* for constant behavior
*roslaunch ow atacama_y1a.launch 
In a separate terminal :
*./grind_action_client.py 
* ./dig_circular_action_client.py  (you can also use the dig_linear service)
* ./discard_action_client.py
*  ./dig_circular_action_client.py (you can also use the dig_linear service)
* ./deliver_action_client.py

changing planner to RRT* for consistent deliver and discard behavior

---

oceanwaters/doc/setup_dev_env.md

The change is only an update to the installation instructions for Plexil.
The test is to update your Plexil installation to 4.6 (see my email "Please update PLEXIL" of 5/10) and then run the ReferenceMission1 plan.  It should behave as before.

Update to Plexil 4.6

---

ow/CMakeLists.txt
ow_bag_recorder/CMakeLists.txt
ow_dynamic_terrain/CMakeLists.txt
ow_ephemeris/CMakeLists.txt
ow_faults_detection/CMakeLists.txt
ow_faults_injection/CMakeLists.txt
ow_gazebo_plugins/CMakeLists.txt
ow_lander/CMakeLists.txt
ow_lander/launch/planning.launch
ow_lander/launch/spawn.launch
ow_power_system/CMakeLists.txt
ow_regolith/CMakeLists.txt
ow_sim_tests/CMakeLists.txt
ow_testbed/CMakeLists.txt
ow_testbed/launch/rviz.launch

| Jira Ticket 🎟️ | [OCEANWATER-981](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-981) |
[ow_autonomy #82](https://github.com/nasa/ow_autonomy/pull/82)
[ow_europa #19](https://github.com/nasa/ow_europa/pull/19)
[irg_open #12](https://github.com/nasa/irg_open/pull/12)
* Updated all CMakesLists.txt following [this ROS Noetic migration step](http://wiki.ros.org/noetic/Migration#Increase_required_CMake_version_to_avoid_author_warning), which has eliminated the following cmake warning.
```
Warnings   << ow_plexil:check /usr/local/home/tstucky/ow/workspace/logs/ow_plexil/build.check.002.log                                          
CMake Warning (dev) at CMakeLists.txt:2 (project): 
Policy CMP0048 is not set: …
```

OceanWATERS 981 Updated all CMakesLists.txt files to required cmake v3.0.2 and other fixes

---

ow_faults_injection/src/FaultInjector.cpp
ow_power_system/src/power_system_node.cpp

| EPIC ⚡ | [OCEANWATER-894](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-894) |
| Jira Ticket 🎟️ | [OCEANWATER-894](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-894) |
* Power fault activation is limited to one per simulation run. Additional activation attempts should be ignored and a warning displayed.
* roslaunch ow europa_terminator_workspace.launch
* In another terminal, navigate to the same directory and activate one of the three power faults:
* rosrun dynamic_reconfigure dynparam set /faults low_state_of_charge_power_failure True
* rosrun dynamic_reconfigure dynparam set /faults instantaneous_capacity_loss_power_failure True
* rosrun dynamic_reconfigure dynparam set /faults thermal_power_failure True
* The …

Oceanwater 894 restrict power faults to one per simulation

---

ow_sim_tests/test/terrain_interaction.py
ow_sim_tests/test/terrain_interaction.test

| Jira Ticket 🎟️ | [OCEANWATER-974](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-974) |
* In the test_06_deliver, following the call to _assert_scoop_regolith_containment, added additional assert that checks all regolith is now contained within the volume of the sample dock
* Approach to check point inside the volume: special case (axis aligned), this will not work well when lander land on sloped/rocky surface. Removed axis aligned approach. Added general case (oriented rectangle box) apply dot product method to check if the point inside the dock
* run the following command in the Terminal
* ```rostest ow_sim_tests …
```

OCEANWATER-974 terrain interaction improvement test

---

ow_dynamic_terrain/README.md
ow_dynamic_terrain/src/DynamicTerrainModel.cpp
ow_dynamic_terrain/src/DynamicTerrainVisual.cpp

| EPIC ⚡ | [OCEANWATER-703](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-703) |
| Jira Ticket 🎟️ | [OCEANWATER-538](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-538) |
* Ogre's internal normal map is applied to any terrain using texture unit `ow_dynamic_terrain_normal_map`. It is updated every time the terrain is modified.
* You must also use the branch from the ow_europa sibling PR: https://github.com/nasa/ow_europa/pull/20
* Run anything that modifies the atacama or terminator_workspace terrains. You should now see the normals and, consequently, the shading being updated on the terrain. Don't confusing shading with shadows; shadows were already working.

Oceanwater 538 ow dynamic terrain modifies normal maps

---

ow_lander/scripts/action_trajectories.py

| Jira Ticket 🎟️ | [OCEANWATER-1046](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1046) |
* changing guarded move planner to rrt star for consistent paths 
Tests: 
cd ow_simulator/ow_lander/scripts
./guarded_move_action_client.py 1.7 0.3 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.7 -0.3 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.9 -0.4 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.9 0.5 0.5 0 0 1 0.7
./guarded_move_action_client.py 1.7 0.0 0.5 1 1 1 0.7
./guarded_move_action_client.py 1.7 0.0 0.5 0.5 -0.5 1 0.8 
./guarded_move_action_client.py 1.78 -0.20 -0.12 0.00 0.00 1.00 0.50
./guarded_move_action_client.py 1.5 -0.20 -0.12 0.00 0.00 1.00 0.50
--

 making planner rrt star for guarded move for consistant planning

---

ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_power_system/config/system.cfg

* Changes max temperature threshold of battery from 50 C to 70 C, per advice from @chetankul 
* Changes base voltage from 3.2 to 2.8, per advice from @chetankul 
* 
* catkin build
* start any simulator world
* start ow_plexil
* run the plan Continuous.plx
* In a new terminal, `rostopic echo /power_system_node/battery_temperature`
* In a new terminal, `rostopic echo /faults/power_faults_status`
* Inject a high power draw of ~30 watts
* Watch the battery temperature and power fault status.  The former should start around 20 and the latter should be 0.  The temperature should steadily increase, and within a few minutes reach 70.  When it does, the power fault status should be 1.   (Before this fix, 50 was the threshold temperature).
NOTE: there is no test for the base voltage change.

Updated battery values

---

ow_power_system/include/PowerSystemNode.h
ow_power_system/src/PowerSystemNode.cpp

| Jira Ticket 🎟️ | N/A |
* Very small change, simply updated a variable name as well as the error message when a custom fault file fails to open. It now displays the path attempted to reach the file rather than just the file name, making it easier to pinpoint possible problems in the code.
* roslaunch ow europa_terminator_workspace.launch
* In the RQT window, navigate to the Dynamic Reconfigure tab, then to the faults section. Scroll down to the custom faults section.
* Input an invalid file name to the `custom_fault_profile` text box, then check the `activate_custom_fault` box and observe the terminal.
* The terminal should output an error message that includes the full path to the file that was attempted to open.

Update fault directory error msg

---

ow_lander/CMakeLists.txt
ow_lander/action/LightSetIntensity.action
ow_lander/launch/spawn.launch
ow_lander/scripts/light_set_intensity_action_client.py
ow_lander/scripts/light_set_intensity_action_server.py

| Jira Ticket 🎟️ | [OCEANWATER-935](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-935) |
* Lander light set intensity ROS Action added. 
1. Launch the world of your choice.
`roslaunch ow atacama_y1a.launch`
2. Tilt mast down so that lander lights are easily visible against the lander body.
`./antenna_pan_tilt_action_client.py 0.0 1.5`
3. Test action client's help message. You should see a brief description of the client, and its arguments.
`./light_set_intensity_action_client.py --help`
4. Test changing the values of both lights as you'd like, i.e. 
```
./light_set_intensity_action_client.py left 0.6 …
```

Oceanwater 935 - LightSetIntensity action

---

ow_gazebo_plugins/src/BalovnevModelPlugin/BalovnevModelPlugin.cpp
ow_gazebo_plugins/src/BalovnevModelPlugin/BalovnevModelPlugin.h

| EPIC ⚡ | [OCEANWATER-1069](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1069) |
| Jira Ticket 🎟️ | [OCEANWATER-1067](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1067) |
* During a dig when the scoop's velocity reverses direction, the Balovnev forces will be set to zero. 
Repeat essentially the same test for [PR#277](https://github.com/nasa/ow_simulator/pull/277), only watching the `balovnev_analysis.perspective` is optional.
1. Call an unstow, grind, and a shallow dig. 
`./unstow_action_client.py && ./grind_action_client.py && ./dig_linear_action_client.py 1.46 0.0 0.01 0.1 -0.1`
The scoop should make it through the material with no trouble. 
2. Call a deeper dig 
`./dig_linear_action_client.py 1.46 0.0 0.01 0.1 -0.2`
Unlike the test …

OCEANWATER-1067 Naive solution to scoop pushback

---

ow_sim_tests/test/action_testing.py

* A condition failure will not be raised until the action completes
* Overtime actions are now allowed to complete
Run the two action calling tests. Testing the failure conditions is unnecessary and may be difficult. Just make sure the tests execute normally. If a failure does happen to occur (i.e. regolith falls out of scoop during a dig/transfer) you should still see the action complete.
1. Run sample collection test
```
rostest ow_sim_tests sample_collection.test
```
2. Run arm check action test
```
rostest ow_sim_tests arm_check_action.test
```

Action condition failures wait for action completion

---

ow_lander/launch/spawn.launch
ow_lander/scripts/state_publisher.py
owl_msgs/CMakeLists.txt
owl_msgs/msg/ArmJointPositions.msg
owl_msgs/msg/ArmJointTorques.msg
owl_msgs/msg/ArmJointVelocities.msg
owl_msgs/msg/PanTiltPosition.msg

| EPIC ⚡ | [OCEANWATER-934](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-934) |
| Jira Ticket 🎟️ | [OCEANWATER-1017](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1017) |
* Publish specific arm and antenna state messages to unify with OWLAT interface
* Launch OceanWATERS sim and `rostopic echo` the following topics:
* /arm_joint_positions
* /arm_joint_torques
* /arm_joint_velocities
* /pan_tilt_position

Oceanwater 1017 arm antenna telemetry unification

---

ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp

| Jira Ticket 🎟️ | [OCEANWATER-1077](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1077) |
| Jira Ticket 🎟️ | [OCEANWATER-1086](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1086) |
Bugfix for issues with camera fault detection that was causing spurious warnings and intermittent fault reports when camera faults where not injected. The issue seemed to stem from asynchronicity in the timer-triggered fault detection routine and the intervals in which camera trigger and camera raw data where being reported.
* Defined a threshold constant for maximum allowed time delay between a camera_trigger message and camera_raw message.
* Simplified the error checking inequality to use the threshold constant.
* ~~Changed error checking callback to only run after a camera trigger, and with …

limit camera fault detection to timer

---

ow_lander/CMakeLists.txt
ow_lander/scripts/state_publisher.py
owl_msgs/CMakeLists.txt
owl_msgs/msg/ArmPose.msg
owl_msgs/package.xml

| EPIC ⚡ | [OCEANWATER-934](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-934) |
| Jira Ticket 🎟️ | [OCEANWATER-1021](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1021) |
* Added /arm_pose topic
* rostopic echo /arm_pose
* ./guarded_move_action_client.py
Note that the final position of guarded_move is similar to the position of /arm_pose because guarded_move shows the position of l_scoop_tip while /arm_pose shows the position of l_scoop. Both positions are relative to base_link.

Oceanwater 1021 implement arm pose

---

ow_faults_detection/CMakeLists.txt
ow_faults_detection/README.md
ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/msg/PTFaults.msg
ow_faults_detection/src/FaultDetector.cpp
owl_msgs/CMakeLists.txt
owl_msgs/msg/PanTiltFaultsStatus.msg

| EPIC ⚡ | [OCEANWATER-934](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-934) |
| Jira Ticket 🎟️ | [OCEANWATER-1011](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1011) |
| Github :octocat:  | [OCEANWATER-1011_implement_telemetry_pan_tilt_faults_status](https://github.com/nasa/ow_simulator/tree/OCEANWATER-1011_implement_telemetry_pan_tilt_faults_status) |
Mostly artifact renaming and updating message definitions.
**This issue has a corresponding and required branch on [ow_autonomy](https://github.com/nasa/ow_autonomy/tree/OCEANWATER-1011_implement_telemetry_pan_tilt_faults_status).**
* Renamed the `PTFaults` message to `PanTiltFaultsStatus` and updated all references in source and documentation.
* Moved `PanTiltFaultsStatus.msg` to the …

update pan tilt artifacts to unified telemetry standard

---

ow_lander/scripts/arm_move_cartesian_guarded.py
ow_lander/scripts/lander_action_servers.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/arm_interface.py
ow_lander/src/ow_lander/constants.py
ow_lander/src/ow_lander/ground_detector.py
ow_lander/src/ow_lander/mixins.py
ow_lander/src/ow_lander/trajectory_planner.py
owl_msgs/CMakeLists.txt
owl_msgs/action/ArmMoveCartesianGuarded.action

| Jira Ticket 🎟️ | [OCEANWATER-945](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-945) |
* Added ArmMoveCartesianGuarded
* There is now a mixin for arm actions that modify pose. 
* Reduced code repetition where possible between ArmMoveCartesian and actions not yet added (this will likely be on-going). 
@anthonykoutroulis To save your own time, please only perform a review of the code.
@kmdalal Perform the following tests, and review the code at your discretion.
Test help message and proof-read
```
$ rosrun ow_lander arm_move_cartesian_guarded.py --help  
usage: arm_move_cartesian_guarded.py [-h] [--frame {0,1}] [--relative] [-x X] [-y …
```

Oceanwater 945 ArmMoveCartesianGuarded added

---

ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp
ow_power_system/CMakeLists.txt
ow_power_system/README.md
ow_power_system/include/PowerSystemNode.h
ow_power_system/package.xml
ow_power_system/src/PowerSystemNode.cpp
owl_msgs/CMakeLists.txt
owl_msgs/msg/BatteryTemperature.msg
owl_msgs/msg/RemainingUsefulLife.msg
owl_msgs/msg/StateOfCharge.msg

| EPIC ⚡ | [OCEANWATER-934](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-934) |
| Jira Ticket 🎟️ | [OCEANWATER-1023](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1023) |
| Jira Ticket 🎟️ | [OCEANWATER-1024](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1024) |
| Jira Ticket 🎟️ | [OCEANWATER-1025](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1025) |
**This issue has a corresponding and required branch on [ow_autonomy](https://github.com/nasa/ow_autonomy/pull/104).**
* Create messages for BatteryTemperature, RemainingUsefulLife, and StateOfCharge in the `owl_msgs` package according to the Telemetry Unification Doc.
* Change existing power_system_node messages to publish without the `/power_system_node` prefix.
* Update …

Oceanwater 1023-1025 battery telemetry unification

---

ow_lander/CMakeLists.txt
ow_lander/action/CameraCapture.action
ow_lander/action/CameraSetExposure.action
ow_lander/scripts/camera_capture_action_client.py
ow_lander/scripts/camera_set_exposure_action_client.py
ow_lander/scripts/deliver_action_client.py
ow_lander/scripts/dock_ingest_sample_action_client.py
ow_lander/scripts/lander_action_servers.py
ow_lander/scripts/stop_action_client.py
ow_lander/scripts/stow_action_client.py
ow_lander/scripts/unstow_action_client.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/server.py

| Jira Ticket 🎟️ | [OCEANWATER-1092](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1092) |
This PR is accompanied by https://github.com/nasa/ow_autonomy/pull/105
* Removed exposure from CameraCapture action and created CameraSetExposure action

Oceanwater 1092 move exposure to its own action

---

ow_lander/action/GuardedMove.action
ow_lander/scripts/arm_find_surface.py
ow_lander/scripts/guarded_move_action_client.py
ow_lander/scripts/lander_action_servers.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/common.py
ow_lander/src/ow_lander/constants.py
ow_lander/src/ow_lander/frame_transformer.py
ow_lander/src/ow_lander/math3d.py
ow_lander/src/ow_lander/mixins.py
ow_lander/src/ow_lander/trajectory_planner.py
owl_msgs/CMakeLists.txt
owl_msgs/action/ArmFindSurface.action

| Jira Ticket 🎟️ | [OCEANWATER-949](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-949) |
* **ArmFindSurface** action added
* Fixed some potential bugs in mixins.py
* tf2 for Python appears to be missing 3D math operations for geometry_msgs types that are otherwise available in C++. A math3d module has been created to handle these kind of operations.
* Deprecated GuardedMove. 
* _Should it also print a deprecated warning when used?_
Your **ow_autonomy** repo should be on the epic branch, `OCEANWATER-933-command-unification-epic`, when testing.
Try it out and make sure the language makes sense.
```
rosrun ow_lander arm_find_surface.py --help
```
Launch atacama_y1a …

Oceanwater 949 - ArmFindSurface

---

ow_lander/scripts/lander_action_servers.py
ow_lander/scripts/pan_tilt_move_cartesian.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/common.py
ow_lander/src/ow_lander/frame_transformer.py
ow_lander/src/ow_lander/math3d.py
ow_lander/src/ow_lander/mixins.py
owl_msgs/CMakeLists.txt
owl_msgs/action/PanTiltMoveCartesian.action

| Jira Ticket 🎟️ | [OCEANWATER-879](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-879) |
* **PanTiltMoveCartesian** action added
* Antenna move logic collected into a mixin shared by both antenna move actions.
Ensure your **ow_autonomy** is on the latest commit of the epic branch, [OCEANWATER-933-command-unification-epic](https://github.com/nasa/ow_simulator/tree/OCEANWATER-933-command-unification-epic), then rebuild. 
Launch atacama_y1a along with an RQT GUI. 
Check that the language makes sense 
```
rosrun ow_lander pan_tilt_move_cartesian.py --help
```
Request an impossible view position. Since pan has full 360 coverage, I believe tilt is the only value that …

Oceanwater 879 PanTiltMoveCartesian

---

.gitignore
ow_lander/scripts/lander_action_servers.py
ow_lander/scripts/pan.py
ow_lander/scripts/tilt.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/mixins.py
owl_msgs/CMakeLists.txt
owl_msgs/action/Pan.action
owl_msgs/action/Tilt.action

| Jira Ticket 🎟️ | [OCEANWATER-1104](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1104) |
* Separate Pan and Tilt actions and user scripts.
1. Build this branch clean along with the `OCEANWATER-933-command-unification-epic` branch of ow_autonomy.
2. Start any simulator world.
3. Try the new `pan.py` and `tilt.py` scripts with the `-h` option, with no arguments, and with values of your choosing.
NOTE: Most of the code has been dumbly factored out of the `AntennaPanTilt` action, and could perhaps be improved (now or in a future iteration).

Oceanwater 1104 separate pan and tilt actions

---

ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp

This is strictly a code cleanup of the fault detector module. A lot of redundant publishing functions were introduced during telemetry unification, but the components essentially all do the same thing: set flags based on fault logic matching the component's fault message (from owl_msgs), similarly update system faults message, and publish the messages with values that directly correspond to the fault flags.
This PR restructures the code around that design and uses a single generic `publishFaultMessage` function and removes individual publishing functions
* Update component listeners to set fault flags with a standardized format
* Introduce a generic `publishFaultsMessage` function which is called whenever a listener updates fault flags
* Remove specific publishing messages and state …

Oceanwater 1100 refactor fault publishing

---

ow_power_system/src/PowerSystemNode.cpp

This change makes the power test easier, and allows RQT Plot to handle battery topics.
* Timestamps of the present time are given to battery topics before they are published
Perform optional step 8.1 of [Test 8 - Power System](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST-011-8+Power+System). If the values show up in the plot, then the test passes.

Add Timestamps to Battery Topics

---

ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/frame_transformer.py

Jira Ticket 🎟️  [OCEANWATER-1115](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1115)
* Increased the default timeout for frame transforms from 0.1 to 0.4 seconds.
1. Launch atacama_y1a
2. Grind out a trench `rosrun ow_lander task_grind.py`
3. Call scoop circular as many times as needed `rosrun ow_lander task_scoop_circular.py`
The test fails if this error appears for any of the calls to TaskScoopCircular.
```
[ERROR]: FrameTransfomer.transform failure: "world" passed to lookupTransform argument target_frame does not exist.
```

increased default frame transform timeout

---

ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/math3d.py
ow_lander/src/ow_lander/mixins.py

Jira Ticket 🎟️  [OCEANWATER-1112](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1112) 
* If an action's normal/orientation goal is not normalized it will either be rejected or normalized possible. 
* If the normal/orientation consists of all zeroes, the action is aborted with an error.
* If the above is not true but the normal/orientation is non-normalized, it is normalized and a warning is logged.
1. Start any simulator world
2. Trigger the zero-quaternion error `rosrun ow_lander arm_move_cartesian.py -x 1.8 -z 0.5 -q 0 0 0 0`
Arm should not move and output will be
```
[INFO:/lander_action_servers] ArmMoveCartesian action started
[ERROR:/lander_action_servers] ArmMoveCartesian: Aborted - orientation is the zero-quaternion and cannot represent a rotation …
```

Oceanwater 1112 - Validate and normalize quaternions and unit vectors

---

ow_lander/src/ow_lander/actions.py
owl_msgs/action/LightSetIntensity.action

| Jira Ticket 🎟️ | [OCEANWATER-1122](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1122) |
* Removed `success` and `message` from LightSetIntensity's Result. This also unify's it with JPL's testbed. 
1. Tilt mast down so the lights can be seen `rosrun ow_lander pan_tilt_move_joints.py 0 1.2`
2. Turn off the left light `rosrun ow_lander light_set_intensity.py left 0`
The left light turns off and you will see
```
[INFO:/lander_action_servers] LightSetIntensity action started
[INFO:/lander_action_servers] LightSetIntensity: Succeeded - left light intensity set successfully.
[INFO:/lander_action_servers] LightSetIntensity action complete
```
Messages from …

Removed redundant Result parameters from LightSetIntensity

---

ow_lander/scripts/lander_action_servers.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/common.py
ow_lander/src/ow_lander/frame_transformer.py
ow_lander/src/ow_lander/mixins.py
ow_lander/src/ow_lander/trajectory_planner.py

Jira Ticket 🎟️ | [OCEANWATER-1119](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1119)
@mikedalal Only perform the test and report on results.
@mogumbo Only review the code (and approach).
* `rospy.Time.now()` used in favor of `rospy.Time(0)`. 
* Increased the default timeout of FrameTransformer to 1 second. 
* Made timestamp and non-optional parameter for FrameTransformer methods, which makes it easier to understand what a method call is doing. 
The following actions may use a frame transform depending on the parameters passed: TaskScoopCircular, TaskScoopLinear, TaskDiscardSample, ArmMoveCartesian, ArmMoveCartesianGuarded, ArmFindSurface, and PanTiltCartesian. This test will call each one with the appropriate parameters to make it uses a frame transform. The test passes if no …

More rigorous transform waiting

---

ow_lander/config/ros_controllers.yaml
ow_lander/src/ow_lander/arm_interface.py

* [OW-1090](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1090) - follow_joint_trajectory action server usually results in an error code
* [OW-1064](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1064) - Arm trajectories sometimes cannot be stopped
* [OW-1097](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1097) - /arm_controller/follow_joint_trajectory action sometimes returns a result before trajectory has completed
* The `goal_tolerance` defined in `ros_controllers.yaml` is now used instead of being overridden by a much smaller value in a method call. This fixes GOAL_TOLERANCE_VIOLATION error code resulting for stow, unstow, and likely other actions. 
* All values of `traj_tolerance` defined in `ros_controllers.yaml` changed to zero, effectively disabling path …

Hotfix - Work-around for follow joint trajectory commonly resulting in error code

---

ow_gazebo_plugins/src/CMakeLists.txt
ow_gazebo_plugins/src/OWLightControlPlugin/CMakeLists.txt
ow_gazebo_plugins/src/OWLightControlPlugin/OWLightControlPlugin.cpp
ow_gazebo_plugins/src/OWLightControlPlugin/OWLightControlPlugin.h
ow_lander/materials/scripts/ow_lander.frag
ow_lander/materials/scripts/ow_lander.material
ow_lander/src/ow_lander/actions.py
ow_lander/urdf/lander.xacro

| Jira Ticket 🎟️ | [OCEANWATER-1120](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1120) |
* Control light intensities by setting an Ogre-controlled shader uniform instead of a custom uniform. This ensures that light intensities go to the correct lights.
* You will also need sibling PR: https://github.com/nasa/ow_europa/pull/23
* Run any ow sim world
* rosrun ow_lander light_set_intensity.py left 0.5
* Use rqt Message Publisher to set antenna tilt to 1.3
* Use rqt Message Publisher to set antenna pan to 1.0
* Use rqt Message Publisher to set antenna pan to -1.0
Without the PR you will see light intensities on top of the lander flicker between lights. With this PR both light intensities stay with the correct lights.

Oceanwater 1120 light params switch lights

---

ow_gazebo_plugins/src/BalovnevModelPlugin/BalovnevModelPlugin.cpp

| EPIC ⚡ | [OCEANWATER-1134](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1134) |
| Jira Ticket 🎟️ | [OCEANWATER-1069](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1069) |
`ResetPhysicsState` was causing the scoop to be pushed towards the lander at the start of a perpendicular **TaskScoopCircular**. It is not clear why this happened, but the intention behind the call was to prevent the scoop from moving backwards as a result of dig forces, and this is already accomplished by simply setting dig forces to zero during backward motion.
Additionally, the backward motion if-statement is entered during non-dig trajectories and even while the scoop is stationary. The former due to any downward arc of the scoop being detected as a dig, and the …

ResetPhysicsState call removed for more consistent scoop motion

---

ow_lander/scripts/task_grind.py
ow_lander/scripts/task_scoop_circular.py
ow_lander/scripts/task_scoop_linear.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/constants.py
ow_lander/src/ow_lander/math3d.py
ow_lander/src/ow_lander/trajectory_sequence.py
ow_lander/urdf/lander.xacro

Jira Ticket 🎟️ | [OCEANWATER-1131](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1131)
@anthonykoutroulis Please review code, testing is optional.
@kmdalal Please perform tests and review the design of each of the 3 trajectories. Code review is optional, but some of the contents of the `plan_trajectory` methods for the 3 actions may be helpful towards understanding trajectory design. 
* Trajectories for **TaskGrind**, **TaskScoopCircular**, and **TaskScoopLinear** all rebuilt such that:
* Commanded depths will be accurate assuming the provided ground_position (or z-coordinate) are accurate.
* Consistent trajectory shape across the workspace. _e.g. The shape of a TaskScoopLinear at coordinate (1.7, 0.0) will be the same (1.7, 0.4)_
* A reference link, l_grinder_tip, added to the …

Improved trajectory accuracy for all trenching commands

---

ow_lander/scripts/task_grind.py
ow_lander/scripts/task_scoop_circular.py
ow_lander/scripts/task_scoop_linear.py
ow_lander/src/ow_lander/actions.py

| EPIC ⚡ | [OCEANWATER-1146](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1146) |
| Jira Ticket 🎟️ | [OCEANWATER-1153](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1153) |
* X and Y for all dig actions (TaskGrind, TaskScoopLinear, and TaskScoopCircular) now correspond to the center of their resulting trench.
* This allows for X and Y values used for a TaskGrind to be used for either a TaskScoopLinear or TaskScoopCircular without adjustment (see Caveat).
* Default action client script values updated to work with new semantics. 
The `length` value used for a TaskGrind cannot in general be used for a TaskScoopLinear in the same spot. This is because the TaskGrind `length` is the distance between the grinder entry point and its exit point, but …

All dig points now correspond to the center of the trench

---

ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/include/PowerSystemPack.h
ow_power_system/include/PredictionHandler.h
ow_power_system/src/PowerSystemNode.cpp
ow_power_system/src/PowerSystemPack.cpp
ow_power_system/src/PredictionHandler.cpp

| EPIC ⚡ | [OCEANWATER-994](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-994) |
| Jira Ticket 🎟️ | [OCEANWATER-1140](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1140) |
* The current iteration of OW-994 does not publish prediction data in a timely manner due to the way its main power system loop operates.
* It sends input data to all asynchronous prognosers at once, but then waits until all prognosers return predictions to continue the loop. This is infeasible when publications are expected at a rate of 0.5Hz, as the return time for 24 prognoser predictions can surpass 20 seconds.
* This PR fully reworks the power system loop so that data is published via rostopics at a rate of 0.5Hz, consistent with the rate of …

Oceanwater-1140: Re-sync topic publication rate

---

ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/include/PowerSystemPack.h
ow_power_system/src/PowerSystemNode.cpp
ow_power_system/src/PowerSystemPack.cpp

| EPIC ⚡ | [OCEANWATER-994](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-994) |
| Jira Ticket 🎟️ | [OCEANWATER-1151](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1151) |
* [OW-994](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-994) currently does not properly handle the mechanical power conversion when arm operations induce a power draw on the battery.
* It duplicates the mechanical power across every node, i.e. a 10W draw as a result of mechanical power applies a 10W draw to each node in the pack, regardless of the number of nodes. For example, a 24-node pack would have the equivalent of a 240W draw applied to it.
* This PR fixes the mechanical power handling primarily, though it also removes the …

Oceanwaters-1151: Pack-model mechanical power handling

---

ow_faults_injection/include/ow_faults_injection/JointsFaults.h
ow_faults_injection/src/JointsFaults.cpp

| Jira Ticket 🎟️ | [OCEANWATER-975](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-975) |
* Have the Joint Faults module subscribe to the original Joint States message, rather than just the gazebo sim updates.
* Change the /flags/joint_states publishing to happen as Joint States messages are received (same rate), rather than on every update
* Flags are still internally updated at sim time.
* Fault detector unchanged, but now /system_faults_status publishes at the correct 50Hz, corresponding to the rate the lander updates rather than as fast as it can to keep up with gazebo sim ticks (was ~400Hz)
* Run a scenario, ie: `roslaunch ow atacama_y1a.launch`
* In another terminal, monitor the system faults message content: `rostopic echo /system_faults_status`
* In another terminal, …

Oceanwater 975 limit system faults publish rate

---

ow/launch/common.launch
ow_faults_injection/include/ow_faults_injection/FaultInjector.h
ow_faults_injection/src/FaultInjector.cpp

| Jira Ticket 🎟️ | [OCEANWATER-1162](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1162) |
The `/StereoCamera/left/camera_info` and `/StereoCamera/left/image_raw` topics were previously not synchronized, resulting in  fault injection only suppressing the image_raw topic and causing a repeated ros warning. Fault injection 
has been updated to also suppress camera_info when during a trigger fault.
* Launch a sim in a terminal
* Monitor the fault topics in other terminal/s (ie: `rostopic echo /system_faults_status`)
* In rqt, activate the /StereoCamera/left/image_trigger topic
* In rqt's Dynamic Reconfigure pane, under Faults, activate the camera_left_trigger_failure fault.
* Observe, for a minute or two, the console output of the simulation terminal.
* Observe that the warning does …

Oceanwater 1162 camera sync warning

---

ow_sim_tests/test/action_testing.py
ow_sim_tests/test/arm_check_action.py
ow_sim_tests/test/sample_collection.py

| Jira Ticket 🎟️ | [OCEANWATER-1166](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1166) |
- The old command names were incompatible with the new action interface in Release 11 and were causing functional issues. The update fixed the action name issue and transferred all goal parameters to new format. The changes should ensure the same test, arm_check_action.test and sample_collection.test which support the old version and now work for Release 11.
* rostest ow_sim_tests arm_check_action.test ignore_action_checks:=true
- rostest ow_sim_tests sample_collection.test ignore_action_checks:=true
test_06_task_scoop_circular in sample_collection.test might result …

Oceanwater 1166 update action rostests

---

ow_lander/scripts/arm_move_joint.py
ow_lander/scripts/arm_move_joints.py
ow_lander/src/ow_lander/trajectory_sequence.py

Jira Ticket 🎟️ | [OCEANWATER-1110](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1110)
* Modernized action client interfaces of `arm_move_joint.py` and `arm_move_joints.py`
* Similar to `arm_move_joints_guarded.py`, relative motion is now set by a command line flag for both actions.
* Similar to `arm_move_joints_guarded.py`, all 6 joint values are required for `arm_move_joints.py`.
* Added a catch statement for a MoveIt exception. It was caught in the old version of the trajectory planner, which means it does not impact the master branch. _If these exceptions go uncaught they will cause the lander action servers to break until simulation is restarted._ 
* Release 12 - Test 4 - ROS Actions
No documentation updates required for these changes as best as I can tell. 
1. Perform steps …

modernized arm_move_joint* action client interfaces

---

ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/src/PowerSystemNode.cpp

| EPIC ⚡ | n/a |
| Jira Ticket 🎟️ | [OCEANWATER-1174](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1174) |
OW-1174 was originally created to discuss and modify the size of the moving average window within ``jointStatesCb`` (which calculates mechanical power from the ``/joint_states`` topic before passing it into GSAP's simple prognoser to affect predictions) because it was discovered to be too large during the PR for OW-994. However, further investigation revealed ``jointStatesCb`` itself may not be working as intended to begin with. Its current implementation runs once every loop in ``ow_power_system``, which is 0.5Hz, but the ``/joint_states`` topic publishes at a rate of 50Hz. Because the subscriber in the power system …

Oceanwater 1174 mechanical power moving average modification

---

ow_sim_tests/scripts/test_camera_set_exposure.py
ow_sim_tests/scripts/test_light_set_intensity.py
ow_sim_tests/scripts/test_task_deliver_sample.py
ow_sim_tests/scripts/test_task_discard_sample.py
ow_sim_tests/scripts/test_task_grind.py
ow_sim_tests/scripts/test_task_scoop_circular.py
ow_sim_tests/scripts/test_task_scoop_linear.py
ow_sim_tests/test/test_camera_capture.test
ow_sim_tests/test/test_camera_set_exposure.test
ow_sim_tests/test/test_light_set_intensity.test
ow_sim_tests/test/test_task_deliver_sample.test
ow_sim_tests/test/test_task_discard_sample.test
ow_sim_tests/test/test_task_grind.test
ow_sim_tests/test/test_task_scoop_circular.test
ow_sim_tests/test/test_task_scoop_linear.test

| Jira Ticket 🎟️ | [OCEANWATER-1175](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1175) |
* Additional tests for actions. 
* Some errors observed during testing: 
- Warning in ros topic [ WARN] [1689639620.134610941, 1916525242.934999943]: The input topic '/StereoCamera/left/camera_info' is not yet advertised
- CameraCapture aborted error (see OW-1186)
* Please let me know if any additional tests are still required to develop. I assumed for this branch all the actions have it own rostest now, except the pan_tile_move actions.
* rostest ow_sim_tests test_task_deliver_sample.test
* rostest ow_sim_tests test_task_discard_sample.test
* rostest ow_sim_tests …

Oceanwater 1175 additional rostests

---

ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/include/PrognoserInputHandler.h
ow_power_system/src/PowerSystemNode.cpp
ow_power_system/src/PrognoserInputHandler.cpp

| EPIC ⚡ | [OCEANWATER-994](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-994) |
| Jira Ticket 🎟️ | [OCEANWATER-1187](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1187) |
Similar to the [PR for OW-1174](https://github.com/nasa/ow_simulator/pull/348), this PR addresses the existing invalid behavior of the ``jointStatesCb`` function within the power system. However, it requires a separate fix due to the differences in the current ``noetic-devel`` version of the power system and the most recent pack model version in [OW-1163](https://github.com/nasa/ow_simulator/tree/OCEANWATER-1163_Improve_Pack_Model_Performance).
Note that this PR is merging into the in-development branch OW-1163, *not* noetic-devel. As such, …

OW-1187: jointStatesCb handling in the pack model

---

ow_dynamic_terrain/src/TerrainModifier.cpp

| Jira Ticket 🎟️ | [OCEANWATER-1191](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1191) |
* Fixed orientation and position problems with dynamic terrain holes.
* There's not a good way to test this without extra changes to other files. Instead, here are some before and after screenshots:
Before/after positioning changes. Positions of holes should be points on a regular grid.
Before/after flip across x-axis. I patched the terrain with europa_test_dem since you can see its proper orientation using `roslaunch ow europa_test_dem.launch`

Oceanwater 1191 fix hole orientation and position

---

ow_sim_tests/scripts/test_arm_move_joints_guarded.py
ow_sim_tests/scripts/test_arm_stop.py
ow_sim_tests/scripts/test_pan_tilt_move_cartesian.py
ow_sim_tests/scripts/test_pan_tilt_move_joints.py
ow_sim_tests/test/test_arm_move_joints_guarded.test
ow_sim_tests/test/test_arm_stop.test
ow_sim_tests/test/test_pan_tilt_move_cartesian.test
ow_sim_tests/test/test_pan_tilt_move_joints.test

| Jira Ticket 🎟️ | [OCEANWATER-1175](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1175) |
Additional testing for `arm_stop`, `arm_move_joints_guarded`, `pan_tilt_move_cartesian` and `pan_tilt_move_joints`.
* `test_pan_tilt_move_cartesian`: Antenna facing the given valid vector in space.
* `test_pan_tilt_move_joints`: Change antenna position by assigning the angle of pan and tilt, The first 9 tests using `PanTiltMoveJointsAction,` in which the pan and tilt move simultaneously, the `test_10` with `PanAction`only move `Pan` and `test_11`with `TiltAction` only move `Tilt`.
* `test_arm_move_joints_guarded`: Scoop tries to dig the ground but with different …

OCEANWATER-1175_Additional_rostests_2

---

ow_dynamic_terrain/include/TerrainModifier.h
ow_dynamic_terrain/src/DynamicTerrainModel.cpp
ow_dynamic_terrain/src/DynamicTerrainVisual.cpp
ow_dynamic_terrain/src/DynamicTerrainVisual.h
ow_dynamic_terrain/src/TerrainModifier.cpp

| Jira Ticket 🎟️ | [OCEANWATER-1142](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1142) |
* Made terrain texture mask, which is updated when heightmap pixels are modified.
* This can't be tested without modifying a material file and shader. Instead, I offer this image as proof that it works. Terrain is drawn in yellow where the mask has been set to 0.

Made terrain texture mask

---

ow_faults_injection/cfg/Faults.cfg
ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/src/PowerSystemNode.cpp

| EPIC ⚡ | n/a |
| Jira Ticket 🎟️ | [OCEANWATER-1196](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1196) |
**Note**: If you are a new reviewer (i.e. anyone except Mike & Thomas), the only test you need to complete is the performance test at the bottom of this PR description.
This PR will be merged into [OW-1163](https://github.com/nasa/ow_simulator/pull/352), ideally before its merge into noetic-devel. It should provide an option for users to reduce the CPU usage of the new multi-cell battery system without fully sacrificing the new changes, while also adding a new fault type only possible with the new implementation.
* A new variable has been added to ``system.cfg``: ``active_models``. This can be set from 1-4, causing …

OW-1196: battery pack partial disabling

---

ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/faults_interface.py
ow_lander/src/ow_lander/mixins.py

| Jira Ticket 🎟️ | [OCEANWATER-1195](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1195) |
The current failure messages relayed from `ow_lander` to `PLEXIL` are still incomplete. This branch primarily aims to establish a robust communication mechanism between the `ow_faults_detection `package and the `ow_lander` package.
Previously, the Arm action servers treated both `ArmExecutionError` and `ArmPlanningError` in the same manner. Furthermore, there was no linkage with the `ow_faults_detection` package. 
This PR introduces a communication method. Here's an overview of the design (Note: Changes currently apply to only `ArmMoveCartesianGurard` and `ArmMoveCartesian`):
* The Arm action can produce outcomes like `ArmExecutionError`, `ArmPlanningError`, or successful action. When ROS …

Oceanwater 1095 failures messages communication

---

ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/src/PowerSystemNode.cpp

| EPIC ⚡ | n/a |
| Jira Ticket 🎟️ | [OCEANWATER-1203](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1203) |
While it's possible to completely disable all functions within the power system, the vast majority of performance issues arise from using GSAP's prognosers for battery predictions. This PR allows for the removal of all prediction work, while still maintaining publications to external components so as to prevent future issues if said external components rely on these publications. Of course, these publications will not be accurate of a real battery, but the published status should be ideal for preventing any errors if the user is not actively utilizing the power system's new modeling capabilities.
* A new flag has been …

Option to disable power system for performance

---

ow_lander/src/ow_lander/server.py

This PR spawned from discussion in #361
* Reset the relevant action group GOAL_ERROR flag at the beginning of an action. 
Launch any simulator world
1. Monitor the system faults topic `rostopic echo /system_faults_status` and the arm faults topic `rostopic echo /arm_faults_status` in two separate terminals. 
2. Call an invalid ArmMoveCartesian `rosrun ow_lander arm_move_cartesian.py`
3. The command will fail. Both topics should show a value of 2. 
4. Call a valid TaskGrind `rosurn ow_lander task_grind.py`
5. The system fault will remain 2, because we are calling an action in a different group (TASK), but arm faults will be reset to 0 at the beginning of the TaskGrind because it uses the arm. Let the TaskGrind complete.
6. Call a valid ArmMoveCertaisn `rosrun ow_lander …

goal errors are cleared at the beginning of the next command

---

ow/launch/common.launch
ow_sim_tests/scripts/sample_collection.py

The new dig model means we dig more shallow trenches at a time. This change ensures we still see a some regolith spawn out of those more shallow digs
* 5x as many regolith particles will spawn for the same amount of dug volume.
* Updates to sample_collection.py, so it works well with the new dig model. 
Run `rostest ow_sim_tests sample_collection.test ignore_action_checks:=True` and ensure it passes.

More regolith for shallow digs

---

ow_faults_detection/src/FaultDetector.cpp
ow_faults_injection/cfg/Faults.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/src/PowerSystemNode.cpp

This PR is critical for Release 12 testing of Fault Detection & Injection, as it allows the user to easily (though artificially) trigger conditions where power faults should occur.
| Jira Ticket 🎟️ | [OCEANWATER-1209](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1209) |
* The user can now inject low state-of-charge, instantaneous capacity loss, and thermal failure. These faults each modify the outputs of GSAP post-prediction, and thus do not interact with GSAP at all. 
* This means their behavior is unrealistic, particularly in regards to RUL (which is not affected at all) and when removing the fault (the predictions immediately return to pre-fault values as if nothing had occurred). Still, it allows users …

OW-1209: Artifical Power Faults

---

ow/launch/common.launch
ow_dynamic_terrain/scripts/modify_terrain_grinder_pub.py
ow_dynamic_terrain/scripts/modify_terrain_scoop_pub.py
ow_gazebo_plugins/src/BalovnevModelPlugin/BalovnevModelPlugin.cpp
ow_gazebo_plugins/src/BalovnevModelPlugin/BalovnevModelPlugin.h
ow_regolith/models/sphere_2cm/model.sdf

* Reduced the rate of deformation messages by a factor of 15. These changes were carried over from a not-ready-for-primetime epic branch. Terry you'll recognize them. 
* Changed blunt edge angle in BalovnevModelPlugin
* Simplified how pushback and pushdown behavior is handled. Now the forces applied by BalovnevModelPugin will max out at some hardcoded value. This is a temporary fix. 
* Fixed the mass of regolith, which was an order of magnitude more massive than it needed to be. 
Run through [Release 12 - Test 7 - Sample Collection](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST-012-7+Sample+Collection). This can serve as both the PR test and the Release 12 test.

Partial fix for scoop stalling

---

ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/mixins.py
ow_lander/urdf/lander_sample_dock.xacro
ow_regolith/src/ContactSensorPlugin.cpp

Jira Ticket 🎟️ | [OCEANWATER-1159](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1159)
@mikedalal Feel free to defer the full review to Terry, seeing as I'm getting this in late before your vacation.
@mogumbo Please test and provide a technical review. 
* DockIngestSample rebuilt to not rely on ContactSensorPlugin
* _Note_ ContactSensorPlugin is still in use for removing regolith that collides with the terrain, and so will not yet be removed at this time.
This rebuild was necessary. The previous approach to DockIngestSample was over complicated and reliant on ContactSensorPlugin, which appears to be bugged. I dug deep into the Gazebo API, but the contact sensor API will randomly fall into a state where there are clearly contacts present on the collision body, but it reports zero …

hotfix/oceanwater 1159 fix for DockIngestSample

---

CONTRIBUTORS.md

This simple fix puts each contributor name on its own line.  Before they all ran together on one line.
Test: impossible to test in GitHub, but open the changed file in any other Markdown viewer.  If it looks fine there, it should look fine on GitHub, especially since the change is so basic.

Fix contributors list formatting

---

ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/mixins.py
ow_lander/src/ow_lander/subscribers.py

I noticed while testing https://github.com/nasa/ow_autonomy/pull/133 that pan/tilt actions would not handle their timeout exception resulting in a long error print-out and the action not being set to aborted. 
In master the output is
```
[ERROR:/lander_action_servers] Exception in your execute callback: Timed out waiting for pan value to reach goal.
Traceback (most recent call last):                                                                                                             
File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop                                 
self.execute_callback(goal)                                                                                                                
File …
```

Antenna exceptions  are now correctly handled by pan/tilt actions

---

ow_ephemeris/README.md
ow_ephemeris/scripts/sunlight_values_for_shaders.py
ow_lander/materials/scripts/ow_lander.frag
ow_lander/materials/scripts/ow_lander.material
ow_lander/materials/scripts/ow_lander.vert
ow_lander/urdf/lander_lights.xacro
ow_lander/urdf/stereo_camera_triggered.xacro

| Jira Ticket 🎟️ | [OCEANWATER-1218](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1218) |
This also requires sibling PR: https://github.com/nasa/ow_europa/pull/30
* Convert light units from lux to W/m^2. Lux is a measure of intensity as perceived by the human eye, which is not so appropriate while we're using simulated cameras for all our images. Lights are now about 3X brighter, which I believe to be a reasonable value based on work on other projects (there's a lot of wiggle-room here depending on specific mission design).
* Use Oren-Nayar reflectance instead of Lambertian. Surfaces now have stronger backscatter and their radiance is slightly view-dependent. All along we had neglected to divide diffuse reflectance by pi. That's fixed now and causes the specular reflection to be …

Oceanwater 1218 improve lighting realism

---

ow_power_system/config/system.cfg
ow_power_system/src/PrognoserInputHandler.cpp

| EPIC ⚡ | [OCEANWATER-697](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-697) |
| Jira Ticket 🎟️ | [OCEANWATER-1232](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1232) |
* Replaces the `baseline_power` configuration parameter with a set of new ones for specific subsystems.
* Edit `ow_simulator/ow_power_system/config/system.cfg` and set the following debug flags to true: `print_debug`, `inputs_print_debug`.
* Start any simulator world.
* Verify that a message similar to the following repeats in the ensuing shell output: 
```
[ INFO]: M00 INPUT power: 6.000000.  volts: 17.603089.  tmp: 17.704866
```
The input power should always be 6.0.

Baseline power draw for multiple subsystems

---

ow_power_system/config/system.cfg
ow_power_system/src/PrognoserInputHandler.cpp

None
* Updated baseline power parameters and values based on the Power Consumption wiki as of 1/25/24.
* Edit `ow_simulator/ow_power_system/config/system.cfg` and set the following debug flags to true: `print_debug`, `inputs_print_debug`.
* Start any simulator world.
* Verify that a message similar to the following repeats in the ensuing shell output: 
```
[ INFO]: M00 INPUT power: 6.000000.  volts: 17.603089.  tmp: 17.704866
```
The input power should always be 6.0.

Updated baseline power categories and values

---

ow_power_system/config/system.cfg
ow_power_system/include/PrognoserInputHandler.h
ow_power_system/src/PrognoserInputHandler.cpp

| EPIC ⚡ | [OCEANWATER-697](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-697) |
| Jira Ticket 🎟️ | [OCEANWATER-702](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-702) |
* Replaced baseline power draw for lights with computed value
* Edit `ow_simulator/ow_power_system/config/system.cfg`
* set `print_debug` and `inputs_print_debug` to true
* Start any simulator world
* Note the input power of 6.0 (watts) printing in the shell.
* Tilt the antenna so that you can see the lander lights shine on the rover: `rosrun ow_lander tilt.py 1.2`
* Note the input power increase above 6.0 while the antenna is moving - this a regression test.
* Noting the lights are initially at full intensity, experiment with different intensities …

Replaced baseline power draw for lights with computed value

---

ow_faults_detection/src/FaultDetector.cpp

| Jira Ticket 🎟️ | [OCEANWATER-1238](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1238) |
* Set camera goal error when there is no image.
* Note: spaces at the ends of lines were automatically removed by Emacs.  Sorry for the distraction!
* This branch supports the same one in `ow_autonomy` but can be merged independently. 
* Build this branch along with the same branch in `ow_autonomy`.
* Do the test in the corresponding `ow_autonomy` PR.

Set camera goal error fault when there is no image

---

ow_faults_detection/src/FaultDetector.cpp

Recently, fault detection was modified to flag a goal error if there is no point cloud received after the camera is triggered.  The problem here is that the check was done *just* after the trigger.  Some point clouds may need more time to arrive.
This "fix" also allowed goal errors to get flagged when the camera was triggered without the `CameraCapture` action, i.e. via a message.  However this is invalid, because goal errors should only be associated with actions.  I.e. actions have goals, pure messages do not.
This hotfix is simply to remove this invalid "fix".
* Try ReferenceMission1 without this hotfix and see most or every CameraCapture fail due to spurious goal errors.
* Apply the hotfix, and ReferenceMission1 should be free of the above problem.
* Inject the camera fault and run …

Hotfix for camera goal error

---

ow_lander/config/ompl_planning.yaml
ow_lander/launch/spawn.launch
ow_lander/src/ow_lander/actions.py

https://github.com/nasa/ow_autonomy/pull/149
* Added a planning time override for TaskDiscardSample only that restores the previous planning time values after completion of the action. 
* Added an `Iteration` termination condition for all RRTStar planned actions. This means the action will either reach the timeout or the iteration limit. 
* Fixed a bug where GuardedMove was not switching the planner back to RRTConnect after concluding. 
1. Have this ow_simulator on planning-timeout-test and ow_autonomy on remove-tailings-default-discard-arguments. Everything else on noetic-devel. 
2. Run ReferenceMission1.plx. several times. This passes so long as there is not a single plan trajectory failure.

Planning timeout increase for TaskDiscardSample

---

ow_power_system/config/system.cfg
ow_power_system/include/PowerSystemNode.h
ow_power_system/include/PrognoserInputHandler.h
ow_power_system/src/PowerSystemNode.cpp
ow_power_system/src/PrognoserInputHandler.cpp

Jira Ticket 🎟️ | [OCEANWATER-1245](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1245)
* All baseline power is now distributed evenly across as power nodes connected in parallel. 
1. Go into `ow_power_system/config/system.cfg` and change `print_debug` to **true** and `inputs_print_debug` to **true**.
2. Start the simulation in any world. You will see the following line continually print. 
```
[ INFO:/power_system_node] M00 INPUT power: 3.975000.  volts: 17.611784.  tmp: 18.298205
```
3. In RQT increase `battery_nodes_to_disconnect` to 1 and tick `disconnect_battery_nodes`. The message should now equal the same power, but distributed across only 3 nodes instead of 4. We can compute what this value should be with 3.975 * 4 / 3 = 5.3
```
[ INFO:/power_system_node] …
```

HOTFIX All baseline power distributed across all 4 power cells

---

ow_lander/config/moveit.rviz
ow_lander/launch/spawn.launch
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/arm_interface.py
ow_lander/src/ow_lander/constants.py
ow_lander/src/ow_lander/mixins.py
ow_lander/urdf/lander.xacro
ow_materials/src/MaterialDistributionPlugin.cpp
ow_materials/src/MaterialIntegrator.cpp

Arm planning now takes place in the correct frame. Workarounds removed in ow_materials
Jira Ticket 🎟️ | [OCEANWATER-1194](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1194)
* Parameterized the lander's position inside of lander.xacro instead of setting lander position with the spawn_model node. This appears to have worked around OW-1194 where the world -> base_link transform is identity. 
* MoveIt plans based on TF transforms, so it's planning frame had to be changed from world -> base_link. This was always a bug, and we were always meant to be planning in the base_link frame, but these two different bugs canceled each other out. By correcting OW-1194 this bug now had to be addressed. 
*  Work arounds for OW-1194 removed in ow_materials code.
No simulation behavior should have …

Fixed tf broadcasting the wrong transform for world -> base_link

---

ow/launch/atacama_y1a.launch
ow/launch/common.launch
ow/launch/europa_terminator.launch
ow/launch/europa_terminator_workspace.launch
ow/launch/europa_test_dem.launch
ow_materials/include/ow_materials/material_mixing.h
ow_materials/src/MaterialDatabase.cpp
ow_materials/src/MaterialDistributionPlugin.cpp
ow_materials/src/MaterialDistributionPlugin.h
ow_materials/src/MaterialIntegrator.cpp
ow_materials/src/material_mixing.cpp
ow_regolith/src/RegolithPlugin.cpp

Jira Ticket 🎟️ | [OCEANWATER-1250](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1250)
Jira Ticket 🎟️ | [OCEANWATER-1235](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1235)
https://github.com/nasa/ow_europa/pull/37
* A roslaunch flag has been added to atacama_y1a.launch (the only world that supports multi-material terrain).
* Any launch files for worlds that do not support either regolith or multi-material terrain have lost flag argument for each respectively and turning those facilities off is now hard-coded in the launch file.  
* The MaterialDistributionPlugin can now be run in a mode that does not material distribution computations, and only computes displaced volume so that RegolithPlugin can still use that data to spawn regolith. 
* Some clean up of roslaunch files. …

Regolith can now be simulated without a material distribution

---

ow/launch/atacama_y1a.launch
ow/launch/europa_terminator.launch
ow/launch/europa_terminator_workspace.launch
ow/launch/europa_test_dem.launch
ow_materials/src/AxisAlignedGrid.h
ow_materials/src/AxisAlignedGrid.tpp
ow_materials/src/MaterialDistributionPlugin.cpp
ow_materials/src/MaterialDistributionPlugin.h
ow_materials/src/MaterialIntegrator.cpp
ow_materials/src/MaterialIntegrator.h
ow_materials/src/VoxelGrid.h
ow_materials/src/VoxelGrid.tpp
ow_materials/src/point_cloud_util.cpp
ow_materials/src/point_cloud_util.h

Jira Ticket 🎟️ | [OCEANWATER-1164](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1164)
https://github.com/nasa/ow_europa/pull/38
* Arguments can now be provided to all world launch files to specify lander initial pose in 3D position and Euler angles.   
* The voxel grid created by MaterialDistributionPlugin can now be positioned relative to a model in the world. 
* The model should be relatively level with the world frame. Only yaw (z-rotation) will be applied to the grid. 
* This allows the voxel grid, and therefore the workspace in which a material distribution will be simulated, to follow the lander to wherever it's moved to. 
For this test we will run ReferenceMission1 in two different locations of atacama_y1a
1. Launch atacama_y1a with the lander in the default position …

Oceanwater 1164 means to reposition lander
