README.md

If these instructions are acceptable I think I should add them to each repo, customizing the link to bug fixes and feature requests for each repo.

Added contribution instructions.

---

ow_dynamic_terrain/scripts/modify_terrain_grinder_pub.py
ow_dynamic_terrain/scripts/modify_terrain_scoop_pub.py
ow_dynamic_terrain/src/TerrainModifier.cpp
ow_lander/urdf/lander.xacro

Same as https://github.com/nasa/ow_simulator/pull/12 but merging it into **melodic-devel**

Oceanwater 471 refine digging collision and deformation

---

ow/launch/common.launch
ow_lander/launch/planning.launch
ow_lander/scripts/mechanical_power_arm.py

This node publishes transient mechanical power on two topics:  /mechanical_power/raw and /mechanical_power/average

Oceanwater 479 publish mechanical power arm

---

ow_lander/scripts/activity_full_digging_traj.py

Test:
- please check that the Stow service runs with no errors. Call Unstow, publish_trajectory, Stow, publish_trajectory. Thanks!

Removed unnecessary line from Stow function

---

ow_lander/scripts/activity_deliver_sample.py
ow_lander/scripts/activity_full_digging_traj.py
ow_lander/scripts/activity_grind.py
ow_lander/scripts/activity_guarded_move.py
ow_lander/scripts/ground_detection.py
ow_lander/scripts/mechanical_power_arm.py
ow_lander/scripts/path_planning_commander.py
ow_lander/scripts/trajectory_publisher.py
ow_lander/scripts/utils.py

I just replaced the comments relative to the functions inputs types with docstrings, as discussed few weeks ago. Please just take a look at it and approve if it looks good.

Oceanwater 508 docstrings

---

ow_faults/cfg/Faults.cfg
ow_faults/src/FaultInjector.cpp

Reverts nasa/ow_simulator#47
merged too soon

Revert "Oceanwater-558 adding grinder fault for arm"

---

pull_request_template.md

Should pre-load the description of a PR when created, users can fill out or delete appropriate sections. Open to adjustments on what a proper PR template should look like

Created new pull request template

---

ow_lander/urdf/lander.xacro

Damaina, these are the changes you made to melodic-devel as part of the speed up I think. Do you think these make sense as part of OCENWATER-518.
I left them unmerged yet to give you the ability to compare

Lander Xacro File Tuning

---

ow_ephemeris/scripts/sunlight_values_for_shaders.py

Forgot this small change in my previous PR.

Updated solar illuminance constant in script.

---

ow_lander/config/ros_controllers.yaml

This should increase the accuracy of the controller. 
Test:
europa_terminator_workspace.launch
roslaunch ow_autonomy autonomy_node.launch plan:="ReferenceMission1.plx"
Check that all services run correctly

Multiplied P gains by 10 for shou,dist,prox,hand joints

---

ow_faults/src/FaultInjector.cpp

| Jira Ticket 🎟️   | [Oceanwater-596](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-596) |
| Github :octocat:  | na |
* fixed variable naming :D
* build works again!

Oceanwater 596 bugfix ow faults breaks build

---

ow_dynamic_terrain/scripts/modify_terrain_patch_sub.py
ow_lander/scripts/activity_guarded_move.py
ow_lander/scripts/mechanical_power_arm.py
ow_lander/scripts/path_planning_commander.py

| Jira Ticket 🎟️   | [Oceanwater-611](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-611) |
| EPIC ⚡| [Oceanwater-577](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |
* Use updated and consistent print and exception syntax.
* Run the sim and check the console for any crashed python scripts. Do roslaunch ow_autonomy autonomy_node.launch and make sure the antenna and arm still move.

Use updated and consistent print and exception syntax.

---

oceanwaters/doc/setup_dev_env.md
ow_power_system/src/power_system_node.cpp

| Jira Ticket 🎟️   | [Oceanwater-621](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-621) |
| EPIC ⚡| [Oceanwater-84](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-84) |
* Implemented SOC functionality
* Updated Setup Dev Environment Instructions
* Replace GSAP repository with v1.0-OW
* Recompile GSAP
* Build/Run OW
* Subscribe to power_system_node/state_of_charge rostopic

OCEANWATER-621 Implement SOC Functionality & GSAP Tagged Branch

---

ow_lander/scripts/activity_guarded_move.py

| Jira Ticket 🎟️   | [OCEANWATER-623](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-623) |
| EPIC ⚡| [OCEANWATER-87](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-87) |
* Removed one line of code that was slowing arm movement
* Run ReferenceMission1.plx and see if it completes successfully.

Removed legacy code for scaling arm velocity.

---

ow_faults/cfg/Faults.cfg
ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp
ow_lander/urdf/lander.xacro

| EPIC ⚡| [OCEANWATER-614 / Implement a force torque sensor for the lander arm ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-614) |
| Jira Ticket 🎟️   | [OCEANWATER-618 / Model potential faults or failures for the ft sensor ](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-618) |
* Remap `/ft_sensor_dist_pitch` topic to `/_original/ft_sensor_dist_pitch`
* Re-route the topic through the FaultsInjector node
* Model three types of faults for the ft_sensor
- zero signal
- signal bias
- increase signal noise
* Grouped ft_sensor faults under one config with master enable flag
* Introduced a random number generator to faults module
* Use normal distribution to simulate increase noise for the sensor
| Fault | Signal |
| …

Oceanwater 618 model potential failures for the ft sensor

---

ow_faults/src/FaultInjector.cpp

*  joint_states_cb was publishing to /faults/system_faults_status without heeding the power fault status.  Some refactoring could remedy this, but I tried simply removing this publish, since the (correct) system fault status is being published by the power monitors.  This has probably affected the publish rate of this telemetry, assuming this is harmless for now.    Perhaps a better solution would be a code refactor.
NOTE: this change just removes line 257 in FaultInjector.cpp.  However, the diff shows many lines changed because my C++ editing mode in Emacs automatically removes extraneous spaces at the end of lines, and there were many of these.
* Same tests as for the parent branch's PR: https://github.com/nasa/ow_simulator/pull/98.  In particular, let the unrecoverable power fault …

Remove erroneous publish of system faults message

---

ow_lander/scripts/trajectory_async_execution.py

| Jira Ticket 🎟️   | [Oceanwater-XXX](url) |
| EPIC ⚡| [Oceanwater-XXX](url) |
* small fix to stop execution for arm rosactions
*

stop during execution

---

ow_lander/scripts/action_dig_circular.py
ow_lander/scripts/action_dig_linear.py
ow_lander/scripts/action_guarded_move.py
ow_lander/scripts/deliver_action_server.py
ow_lander/scripts/dig_circular_action_server.py
ow_lander/scripts/dig_linear_action_server.py
ow_lander/scripts/grind_action_server.py
ow_lander/scripts/guarded_move_action_server.py
ow_lander/scripts/stow_action_server.py
ow_lander/scripts/unstow_action_server.py

| Jira Ticket 🎟️   | [Oceanwater-XXX](url) |
| EPIC ⚡| [Oceanwater-XXX](url) |
* 
Fix index out of range errors. When Planner does not find any valid plans action should be terminated without errors.  
* 
Test 6.4 Index out of range errors should not happen.

fix index out of range error

---

ow_lander/scripts/LanderInterface.py
ow_lander/scripts/deliver_action_client.py
ow_lander/scripts/dig_circular_action_client.py
ow_lander/scripts/dig_linear_action_client.py
ow_lander/scripts/grind_action_client.py
ow_lander/scripts/ground_detection.py
ow_lander/scripts/guarded_move_action_client.py
ow_lander/scripts/stow_action_client.py
ow_lander/scripts/unstow_action_client.py

| Jira Ticket 🎟️   | [Oceanwater-678](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-678) |

Changed python to python2 in several scripts.

---

ow_dynamic_terrain/scripts/modify_terrain_patch_pub.py
ow_lander/scripts/LanderInterface.py
ow_lander/scripts/dig_circular_action_server.py
ow_lander/scripts/grind_action_server.py

| Jira Ticket 🎟️   | [Oceanwater-677](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-677) |
| EPIC ⚡| [Oceanwater-87](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-87) |
* 
* roslaunch ow atacama_y1a.launch 
* Then in another terminal: roslaunch ow_autonomy autonomy_node.launch
* See that the demo completes successfully

Update exception syntax to work with both python2 and python3.

---

ow/rsdf/ball_icefrag.rsdf
ow/rsdf/ball_sand.rsdf
ow/rsdf/ball_snow.rsdf
ow/scripts/spawn_bulk_sample.sh

| EPIC ⚡| [OCEANWATER-680](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-680) |
| Jira Ticket 🎟️   | [OCEANWATER-713](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-713) |
| Github :octocat:  | na |
* Added a script for spawning bulk material into the Gazebo sim.
* Added two directories to the ow directory: rsdf and scripts. rsdf contains Embedded Ruby SDF files that the new script uses.
1. Launch the europa_terminator_workspace world 
`roslaunch ow europa_terminator_workspace.launch`
2. Now we need to get the scoop in an upward facing position ready to receive sample dropped into it. The easiest way to do this is to call dig circular and wait for it to finish. The dig circular does not need to touch the ground, and likely won't in this …

Add bulk sample spawner script

---

pull_request_template.md

| EPIC ⚡| [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX) |
) |
| Jira Ticket 🎟️   | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-XXX)) |
* 
*

Update pull req template for new line

---

README.md
oceanwaters/doc/setup_oceanwaters.md

| EPIC ⚡ | [OCEANWATER-601](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-601) |
| Jira Ticket 🎟️ | [OCEANWATER-577](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-577) |

Added hint for using experimental noetic-devel branch.

---

ow_faults/include/ow_faults/FaultInjector.h
ow_faults/src/FaultInjector.cpp
ow_faults_detection/include/ow_faults_detection/FaultDetector.h
ow_faults_detection/src/FaultDetector.cpp

| EPIC ⚡ | [OCEANWATER-720](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-720) |
| Jira Ticket 🎟️ | [OCEANWATER-720](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-720) |
* moved detection of arms to new node
* detection compares joint states and arm_controller/state
* see tests :https://github.com/nasa/ow_simulator/pull/114

Oceanwater 720 detect arm faults

---

ow_faults/src/JointsFaults.cpp

| EPIC ⚡ | [OCEANWATER-726 / Fault Handling Plans and Patterns](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-726) |
| Jira Ticket 🎟️ | [OCEANWATER-807 / realtime factor cut in half following merge of fault handling changes](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-807) |
* Problem Root Cause: The API `ros::param::param` is rather slow and invoking it with the `BeforePhysicsUpdate` event causes a significant slowdown to the physics update loop.
* Solution: Switched from `ros::param::param` to `ros::param::getCached`. The `getCached` version provides a huge speed as it queries that param value locally which gets updated by ros using a internal subscription.
```bash
roslaunch ow …
```

OCEANWATER-807: Realtime factor cut in half following merge of fault handling changes

---

ow_sim_tests/test/arm_check.py

| EPIC ⚡ | N / A |
| Jira Ticket 🎟️ | [OCEANWATER-850](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-850) |
* arm_check test no longer calls deliver service with parameters
* arm_check now normalizes its joint goals before comparing with the normalized joint states
* arm_check uses arm_deliver_final as the goal for the deliver test
@mogumbo, feel free to just do a code review, if that's all you've got time for.
@anjan1984, when you test this and we merge it into release, then we can count the results as **Tester 3** on the test page.
Perform [OW-TEST-009-3 Sample Collection](https://babelfish.arc.nasa.gov/confluence/display/OCEANWATERS/OW-TEST-009-3+Sample+Collection) using rostest and ensure all tests pass.
```rostest …
```

Oceanwater 850 Fix arm check test calling deliver with parameters

---

ow_lander/materials/scripts/ow_lander.frag

| Jira Ticket 🎟️ | [OCEANWATER-XXX](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-539) |
This work is in support of this other PR: https://github.com/nasa/ow_europa/pull/18

Tune lander shader shadows to use front-face shadow maps.

---

ow_testbed/README.md

| Jira Ticket 🎟️ | [OCEANWATER-964](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-964) |
* Added README.md and COLCON_IGNORE to unused ow_testbed package.

Added README.md and COLCON_IGNORE to unused ow_testbed package.

---

ow_sim_tests/README.md
ow_sim_tests/test/arm_check_action.py
ow_sim_tests/test/arm_check_action.test
ow_sim_tests/test/arm_check_service.py
ow_sim_tests/test/arm_check_service.test
ow_sim_tests/test/fps_monitor.test
ow_sim_tests/test/ft_sensor.test

| Jira Ticket 🎟️ | [OCEANWATER-970](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-970) |
* ROS actions version of arm check test
* run following command in the Terminal  ```rostest ow_sim_tests arm_check_action.test```

ROS actions version of arm check test

---

ow_lander/CMakeLists.txt
ow_lander/action/CameraCapture.action
ow_lander/launch/spawn.launch
ow_lander/package.xml
ow_lander/scripts/camera_capture_action_client.py
ow_lander/scripts/camera_capture_action_server.py

| Jira Ticket 🎟️ | [OCEANWATER-959](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-959) |
* Added CameraCapture action with client and server.
* In another terminal:
* cd src/ow_simulator/ow_lander/scripts
* ./antenna_pan_tilt_action_client.py 1 0.5
* ./camera_capture_action_client.py
* ./camera_capture_action_client.py 0.1  (and other exposures)
* view images in rqt

Oceanwater 959 camera capture action

---

ow_lander/scripts/dock_ingest_sample_action_client.py

* Help message added to dock ingest sample action client
No test needed. This PR is too small.

OCEANWATER-1061 - Help message added to dock ingest sample

---

ow_lander/scripts/arm_move_cartesian_guarded.py
ow_lander/scripts/arm_move_joints_guarded.py
ow_lander/scripts/lander_action_servers.py
ow_lander/src/ow_lander/actions.py
ow_lander/src/ow_lander/mixins.py
owl_msgs/CMakeLists.txt
owl_msgs/action/ArmMoveJointsGuarded.action

| Jira Ticket 🎟️ | [OCEANWATER-948](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-948) |
* **ArmMoveJointsGuarded** action added
* minor reworking of **ModifyJointValuesMixin**
Make sure language and the way in which values are accepted make sense for the action client script. 
```
rosrun ow_lander arm_move_joints_guarded.py --help
```
Perform the following test in atacama_y1a for consistent results
```
rosrun ow_lander arm_move_joints_guarded.py 0 0 0 0 0 0
```
You'll see the following
```
ArmMoveJointsGuarded action started
ArmMoveJointsGuarded: Succeeded - ArmMoveJointsGuarded trajectory completed without breaching force or torque thresholds …
```

Oceanwater 948 ArmMoveJointsGuarded added

---

ow_lander/materials/scripts/ow_lander.frag
ow_lander/materials/scripts/ow_lander.material

| Jira Ticket 🎟️ | [OCEANWATER-1158](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1158) |
This is a code simplification and results in no visual change.

Replace Ogre inverse_texture_size with GLSL textureSize.

---

ow_lander/src/ow_lander/actions.py

Jira Ticket 🎟️ | [OCEANWATER-1183](https://babelfish.arc.nasa.gov/jira/browse/OCEANWATER-1183)
Previously the scoop would initiate its approach towards the surface at the provided **position**. It was never intended to work this way, it should instead begin its approach a **distance** along the anti-normal direction away from **position**. This change makes it so. 
There may be a separate PR for merging this back into noetic-devel because the code has changed enough between the two branches that these changes will unfortunately not carry over directly.
This is a hotfix, so don't forget to have ow_simulator set to this branch, and all the other repos set to `master`.
1. In atacama_y1a `rosrun ow_lander arm_find_surface.py -x 1.6 -y -0.2 -z -0.17 --distance 0.2`.
The scoop should begin its …

HOTFIX ArmFindSurface was not beginning its approach a distance away from surface

---

CONTRIBUTORS.md
README.md
oceanwaters/doc/setup_dev_env.md

* Updated PLEXIL installation instructions for version 6.
* Updated team lists, put into new file `CONTRIBUTORS.md`.

Updated for PLEXIL 6, updated staff list into separate file

---

ow_power_system/config/system.cfg

Updated power consumption values in configuration file to be total power draw of each subsystem, and revised comments accordingly.
The Release 13 power system test, which was revised based on this hotfix and should be done using this hotfix branch.

Updated power consumption values

---

ow_power_system/src/PowerSystemNode.cpp

* Fixed a bug where instantaneous capacity loss and low state of charge being injected on the same battery cycle would cause the low state of charge fault to be ignored. 
* Cleaned up some commented out code.
1. Start the simulator in any world.
2. In a second terminal, monitor the state of charge topic `rostopic echo /battery_state_of_charge/value`
3. Bring up Dynamic Reconfigure in RQT and navigate to the fault menu.
4. In quick succession, tick `instantaneous_capacity_loss` then `low_state_of_charge`.
5. In the terminal printing SOC values, you will should see values immediately drop to about 0.01, then continue dropping by a significant amount each consecutive value (by about 5% of whatever the previous value was). 
```
0.9508093595504761
---
0.9508093595504761
---
0.09006000018358229 …
```

Fixed instantaneous capacity loss overriding low state of charge
